Ads:
  description: Deze app bevat advertenties
  name: Advertenties
DisabledAlgorithm:
  description: Deze app heeft een zwakke beveiligingshandtekening
  name: Ondertekend met een oveilige sleutel
KnownVuln:
  description: Deze app bevat een bekende beveiligingskwetsbaarheid
  name: Bekende Kwetsbaarheid
NoSourceSince:
  name: Geen broncode meer sinds
  description: De broncode is niet meer beschikbaar, geen updates meer mogelijk
NonFreeAdd:
  description: Deze app promoot niet-vrije add-ons
  name: Niet-vrije uitbreidingen
NonFreeAssets:
  description: Deze app bevat niet-vrije elementen
  name: Niet-vrije onderdelen
NonFreeDep:
  description: Deze app vereist andere niet-vrije apps
  name: Niet-vrije afhankelijkheden
NonFreeNet:
  description: Deze app promoot niet-vrije netwerkdiensten
  name: Niet-vrije netwerkdiensten
Tracking:
  description: Deze app houdt je activiteiten bij en rapporteert ze
  name: Tracering
NSFW:
  description: Deze app bevat gegevens die niet overal mag worden gepubliceerd of zichtbaar is
  name: NSFW
TetheredNet:
  description: Deze app is volledig afhankelijk van een bepaalde instantie van een netwerkservice
  name: Gekoppelde Netwerk Diensten
