Connectivity:
  name: Connectiviteit
Development:
  name: Ontwikkeling
Games:
  name: Spellen
Graphics:
  name: Grafisch
Internet:
  name: Internet
Money:
  name: Geld
Multimedia:
  name: Multimedia
Navigation:
  name: Navigatie
Phone & SMS:
  name: Telefoon & SMS
Reading:
  name: Lezen
Science & Education:
  name: Onderwijs & wetenschap
Security:
  name: Beveiliging
Sports & Health:
  name: Sport & Gezondheid
System:
  name: Systeem
Theming:
  name: Themaâ€™s
Time:
  name: Tijd
Writing:
  name: Schrijven
