Connectivity:
  name: ಸಂಪರ್ಕ
Development:
  name: ಅಭಿವೃದ್ಧಿ
Games:
  name: ಆಟಗಳು
Graphics:
  name: ಗ್ರಾಫಿಕ್ಸ್
Internet:
  name: ಇಂಟರ್ನೆಟ್
Money:
  name: ಹಣ
Multimedia:
  name: ಮಲ್ಟಿಮೀಡಿಯಾ
Navigation:
  name: ಸಂಚರಣೆ
Phone & SMS:
  name: ಫೋನ್ ಮತ್ತು SMS
Reading:
  name: ಓದುವಿಕೆ
Science & Education:
  name: ವಿಜ್ಞಾನ ಮತ್ತು ಶಿಕ್ಷಣ
Security:
  name: ಭದ್ರತೆ
Sports & Health:
  name: ಕ್ರೀಡೆ ಮತ್ತು ಆರೋಗ್ಯ
System:
  name: ಸಿಸ್ಟಮ್
Theming:
  name: ಥೀಮ್
Time:
  name: ಸಮಯ
Writing:
  name: ಬರೆಯುವುದು
AI Chat:
  name: AI ಚಾಟ್
App Manager:
  name: ಅಪ್ಲಿಕೇಶನ್ ಮ್ಯಾನೇಜರ್
App Store & Updater:
  name: ಆಪ್ ಸ್ಟೋರ್
Bookmark:
  name: ಬುಕ್ಮಾರ್ಕ್
Browser:
  name: ಬ್ರೌಸರ್
Calculator:
  name: ಕ್ಯಾಲ್ಕುಲೇಟರ್
