Connectivity:
  name: 網絡
Development:
  name: 開發
Games:
  name: 遊戲
Graphics:
  name: 繪圖
Internet:
  name: 互聯網
Money:
  name: 財經
Multimedia:
  name: 多媒體
Navigation:
  name: 導航
Phone & SMS:
  name: 通話與短訊
Reading:
  name: 閱讀
Science & Education:
  name: 科學與教育
Security:
  name: 安全與保安
Sports & Health:
  name: 體育與健康
System:
  name: 系統
Theming:
  name: 主題
Time:
  name: 時間
Writing:
  name: 文書
