Connectivity:
  name: Anslutbarhet
Development:
  name: Utveckling
Games:
  name: Spel
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Pengar
Multimedia:
  name: Multimedia
Navigation:
  name: Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Läsning
Science & Education:
  name: Vetenskap & Utbildning
Security:
  name: Säkerhet
Sports & Health:
  name: Sport & Hälsa
System:
  name: System
Theming:
  name: Temasättning
Time:
  name: Tid
Writing:
  name: Skrivande
AI Chat:
  name: AI-chatt
App Manager:
  name: Apphanteraren
App Store & Updater:
  name: App Store och uppdateringsprogram
Bookmark:
  name: Bokmärke
Browser:
  name: Webbläsare
Calculator:
  name: Kalkylator
Calendar & Agenda:
  name: Kalender och agenda
Cloud Storage & File Sync:
  name: Molnlagring och filsynkronisering
DNS & Hosts:
  name: DNS och värdar
Draw:
  name: Rita
Ebook Reader:
  name: E-boksläsare
Email:
  name: Mejl
File Encryption & Vault:
  name: Filkryptering och valv
File Transfer:
  name: Filöverföring
Forum:
  name: Forum
Gallery:
  name: Galleri
Habit Tracker:
  name: Vanespårare
Icon Pack:
  name: Ikonpaket
Keyboard & IME:
  name: Tangentbord och IME
Launcher:
  name: Startare
Local Media Player:
  name: Lokal mediaspelare
Location Tracker & Sharer:
  name: Platsspårare och delare
Messaging:
  name: Meddelanden
Music Practice Tool:
  name: Muskikövningsapp
News:
  name: Nyheter
Note:
  name: Notera
Online Media Player:
  name: Online mediaspelare
Pass Wallet:
  name: Passplånbok
Password & 2FA:
  name: Lösenord och 2FA
Podcast:
  name: Pod
Public Transport:
  name: Kollektivtrafik
Recipe Manager:
  name: Recepthanterare
Religion:
  name: Religion
Shopping List:
  name: Inköpslista
Social Network:
  name: Socialt nätverk
Task:
  name: Uppgift
Text Editor:
  name: Textredigerare
Translation & Dictionary:
  name: Översättning och ordbok
Unit Convertor:
  name: Enhetskonverterare
Voice & Video Chat:
  name: Röst- och videochatt
VPN & Proxy:
  name: VPN och proxy
Wallet:
  name: Plånbok
Wallpaper:
  name: Tapet
Weather:
  name: Väder
Workout:
  name: Träningspass
