Ads:
  description: Aplicația conține reclamă
  icon: ic_antifeature_ads.png
  name: Reclame
DisabledAlgorithm:
  description: Aplicația are o semnătură slab securizată
  icon: ic_antifeature_disabledalgorithm.png
  name: Algoritm nesigur semnătură
KnownVuln:
  description: Aplicația conține o vulnerabilitate de securitate cunoscută
  icon: ic_antifeature_knownvuln.png
  name: Vulnerabilitate cunoscută
NSFW:
  description: Această aplicație conține conținut care nu ar trebui să fie făcut public sau vizibil peste tot
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Codul sursă nu mai este disponibil, nu mai există posibilitatea de a actualiza.
NonFreeAdd:
  description: Aplicația promovează anexe ce nu sunt software liber
  icon: ic_antifeature_nonfreeadd.png
  name: Anexe ne-libere
NonFreeAssets:
  description: Aceasta aplicație conține resurse ce nu sunt la disponibile la liber
  icon: ic_antifeature_nonfreeassets.png
  name: Resurse ne-libere
NonFreeDep:
  description: Aplicația depinde de alte aplicații ce nu sunt software liber
  icon: ic_antifeature_nonfreedep.png
  name: Dependențe ne-libere
NonFreeNet:
  description: Aplicația promovează sau depinde în întregime de un serviciu de rețea care nu poate fi schimbat sau care nu este liber
  icon: ic_antifeature_nonfreenet.png
  name: Servicii de rețea ne-libere
Tracking:
  description: Aplicația îți înregistrează și raportează activitatea undeva
  icon: ic_antifeature_tracking.png
  name: Urmărire
UpstreamNonFree:
  description: Codul sursa originar nu este în totalitatea lui software liber
  icon: ic_antifeature_upstreamnonfree.png
  name: Surse ne-libere
TetheredNet:
  description: Această aplicație promovează sau depinde în întregime de o anumită instanță a unui serviciu de rețea.
  name: Servicii de rețea captive
