Connectivity:
  name: Conectividade
Development:
  name: Desenvolvemento
Games:
  name: Xogos
Graphics:
  name: Gráficas
Internet:
  name: Internet
Money:
  name: Diñeiro
Multimedia:
  name: Multimedia
Navigation:
  name: Navigación
Phone & SMS:
  name: Teléfono móbil e SMS
Reading:
  name: Lectura
Science & Education:
  name: Ciencia e educación
Security:
  name: Seguranza
Sports & Health:
  name: Deportes e saúde
System:
  name: Sistema
Theming:
  name: Aparencia
Time:
  name: Tempo
Writing:
  name: Escrita
