Categories:
  - Internet
License: GPL-2.0-only
SourceCode: https://github.com/zoff99/MetalabDoorWidget
IssueTracker: https://github.com/zoff99/MetalabDoorWidget/issues

AutoName: MetalabDoorWidget

RepoType: git
Repo: https://github.com/zoff99/MetalabDoorWidget

Builds:
  - versionName: 1.0.1
    versionCode: 10001
    commit: 7623e29bcaf53c1af847e29f41af2fc81bc0bd0b
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.2
    versionCode: 10002
    commit: 1.0.2
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.4
    versionCode: 10004
    commit: 1.0.4
    subdir: app
    gradle:
      - yes

MaintainerNotes: Description and summary in app git repository

ArchivePolicy: 0
AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: 1.0.4
CurrentVersionCode: 10004
