Categories:
  - Sports & Health
License: GPL-3.0-only
AuthorName: Zoff
SourceCode: https://github.com/zoff99/UnderEat
IssueTracker: https://github.com/zoff99/UnderEat/issues
Changelog: https://github.com/zoff99/UnderEat/commits/master/

AutoName: Under Eat

RepoType: git
Repo: https://github.com/zoff99/UnderEat

Builds:
  - versionName: 1.0.4
    versionCode: 10004
    commit: b1ae99a2e948157b6f028c62804a64e67afbaaa1
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.5
    versionCode: 10005
    commit: 4403a4281fa5922eb032451dff468b37db7373e0
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.7
    versionCode: 10007
    commit: a0772206c5c97bd888bb4b21dae4d2f558780baa
    subdir: app
    gradle:
      - yes

  - versionName: 1.0.8
    versionCode: 10008
    commit: cc10d83da2cfe40223f3900042e5daae90cd063c
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags ^[0-9].*
CurrentVersion: 1.0.8
CurrentVersionCode: 10008
