Categories:
  - Location Tracker & Sharer
License: GPL-3.0-only
AuthorName: Zoff
SourceCode: https://github.com/zoff99/ToLoShare
IssueTracker: https://github.com/zoff99/ToLoShare/issues

AutoName: ToLoShare

RepoType: git
Repo: https://github.com/zoff99/ToLoShare.git

Builds:
  - versionName: 1.0.4
    versionCode: 10004
    commit: cc3fc8a3d9dcde3ec500e5a3438499178c84ac28
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.6
    versionCode: 10006
    commit: 26c4b0751ca58614664ff432efd2e68667aee240
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.7
    versionCode: 10007
    commit: 49b070f9f1acfbdf9ccac065933f85d5528d4736
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.8
    versionCode: 10008
    commit: 7b5292b61a3beb5c308a7f71b432cc474eeb327c
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.9
    versionCode: 10009
    commit: f0f8945e2414f3789e5ad3be7355f72374ad2e82
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.11
    versionCode: 10011
    commit: 6474c3caa86572bf33dee5dd840b2a8d9d4ae99b
    subdir: android-refimpl-app/app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags ^[0-9].*
CurrentVersion: 1.0.11
CurrentVersionCode: 10011
