Categories:
  - System
License: Apache-2.0
SourceCode: https://bitbucket.org/oF2pks/fdroid-applications-info/src
IssueTracker: https://forum.xda-developers.com/android/software-hacking/dexdump-xodus-trackers-apk-static-t3833391

AutoName: apps_Packages Info
Description: |-
    Quickly show all possible android states for all installed packages:

    * SharedLibs & uid added
    * Persistent +Stopped +Inactive +Suspended state per app
    * debug or test possible flavour
    * sdk version (sorting option for Oreo/Pie)
    * READ_LOGS if granted
    * system app with locked data
    * ALL ApplicationInfos classic features
    * (full scan classes & trackers via intent/ClassyShark3xodus)

    With minimum of permissions, this app also demonstrates all possible leaks
    that can be done by any installed app with INTERNET granted (and closed
    sources), in order to grab data for profiling.

    (prim-origin https://github.com/MajeurAndroid/Android-Applications-Info)

RepoType: git
Repo: https://bitbucket.org/oF2pks/fdroid-applications-info/src

Builds:
  - versionName: 1.7-9
    versionCode: 9
    commit: v1.7-9
    subdir: app
    gradle:
      - yes

  - versionName: 1.7-10
    versionCode: 10
    commit: v1.7-10
    subdir: app
    gradle:
      - yes

  - versionName: 1.7-11
    versionCode: 11
    commit: v1.7-11
    subdir: app
    gradle:
      - yes

  - versionName: 1.7-12
    versionCode: 12
    commit: v1.7-12
    subdir: app
    gradle:
      - yes

  - versionName: 1.7-13
    versionCode: 13
    commit: v1.7-13
    subdir: app
    gradle:
      - yes

  - versionName: 1.7-14
    versionCode: 14
    commit: v1.7-14
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version v%v
UpdateCheckMode: Tags
CurrentVersion: 1.7-14
CurrentVersionCode: 14
