Categories:
  - System
License: Apache-2.0
AuthorName: Majeur
AuthorEmail: majeur.android@gmail.com
SourceCode: https://github.com/MajeurAndroid/Applications-Info
IssueTracker: https://github.com/MajeurAndroid/Applications-Info/issues

AutoName: Applications Info
Description: |-
  Monitor all available informations about all installed applications or packages
  on a device. You can view the entire AndroidManifest.xml file and get details
  about:

  * Activities
  * Services
  * Providers
  * Receivers
  * Uses permissions
  * Permissions
  * Uses features
  * Configurations
  * Signatures

RepoType: git
Repo: https://github.com/MajeurAndroid/Applications-Info

Builds:
  - versionName: '1.2'
    versionCode: 3
    commit: d3733bae0f23ac758b5ef1dcfd8c8c3ab1aca7ca
    subdir: app
    gradle:
      - yes

  - versionName: '1.3'
    versionCode: 4
    commit: 0e0f44389a197d780828ac6123685b1708e3eb9c
    subdir: app
    gradle:
      - yes

  - versionName: '1.4'
    versionCode: 5
    commit: d2481b8b0261a4cc2f542153edfeb708f7e1b5a0
    subdir: app
    gradle:
      - yes

  - versionName: '1.5'
    versionCode: 6
    commit: 552f2a227373bb1478dc096e101f9e60719ecb3f
    subdir: app
    gradle:
      - yes

  - versionName: '1.6'
    versionCode: 7
    commit: c277503ae3cad667f101d381d3b146bfb0a1b5d2
    subdir: app
    gradle:
      - yes
    prebuild: echo -e "android { lintOptions { disable 'MissingTranslation'\n\ndisable
      'ExtraTranslation' }}" >> build.gradle

ArchivePolicy: 0
AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: '1.6'
CurrentVersionCode: 7
