Categories:
  - Location Tracker & Sharer
License: GPL-3.0-only
AuthorName: Zoff
SourceCode: https://github.com/zoff99/ToLoShare
IssueTracker: https://github.com/zoff99/ToLoShare/issues

AutoName: ToLoShare

RepoType: git
Repo: https://github.com/zoff99/ToLoShare.git

Builds:
  - versionName: 1.0.4
    versionCode: 10004
    commit: cc3fc8a3d9dcde3ec500e5a3438499178c84ac28
    subdir: android-refimpl-app/app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags ^[0-9].*
CurrentVersion: 1.0.4
CurrentVersionCode: 10004
