Categories:
  - File Transfer
  - Internet
License: GPL-3.0-only
AuthorName: Zoff
SourceCode: https://github.com/zoff99/ToFShare
IssueTracker: https://github.com/zoff99/ToFShare/issues

AutoName: ToFShare

RepoType: git
Repo: https://github.com/zoff99/ToFShare.git

Builds:
  - versionName: 1.0.3
    versionCode: 10003
    commit: 2a06497059991c174aefdc58ab9c1a356161c76d
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.4
    versionCode: 10004
    commit: c511c657d61a46b476d8404200a941c2130ea941
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.5
    versionCode: 10005
    commit: c1663f262a1c4c60ec31ed8780179b54ef4d6483
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.6
    versionCode: 10006
    commit: 77813ad33848cbba07d4d46638b36f295eb3f8e8
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.7
    versionCode: 10007
    commit: b54976edbc4b02cf0c6a7e0ff5a4994987b4cb1d
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.8
    versionCode: 10008
    commit: d46de32da921b56a51a27144f0734b29a2e29826
    subdir: android-refimpl-app/app
    gradle:
      - yes

  - versionName: 1.0.9
    versionCode: 10009
    commit: 9be2e11db1d88c5b0ce7491f137cf973ece8d8cd
    subdir: android-refimpl-app/app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags ^[0-9].*
CurrentVersion: 1.0.9
CurrentVersionCode: 10009
