Categories:
  - System
License: GPL-3.0-or-later
SourceCode: https://github.com/tompreuss/APNSettings
IssueTracker: https://github.com/tompreuss/APNSettings/issues

AutoName: APN Settings
Description: Provides a shortcut to the APN Settings portion of Android Settings.

RepoType: git
Repo: https://github.com/tompreuss/APNSettings.git

Builds:
  - versionName: '1.0'
    versionCode: 1
    commit: v1.0
    subdir: app
    gradle:
      - yes

AutoUpdateMode: None
UpdateCheckMode: Tags
CurrentVersion: '1.0'
CurrentVersionCode: 1
