Disabled: Abandonware that depends on Google Play
Categories:
  - System
License: GPL-3.0-or-later
WebSite: https://community.kde.org/Necessitas
SourceCode: https://cgit.kde.org/ministro.git/

AutoName: Ministro configuration tool
Summary: configure Ministroâ€™s default repositories
Description: |-
    This is the configuration utility for [[org.kde.necessitas.ministro]]. You do
    not need to install this (or that) unless another app requests it.

RepoType: git
Repo: https://anongit.kde.org/ministro.git

Builds:
  - versionName: '2.0'
    versionCode: 2
    disable: still just assumes playmarket 7.0
    commit: unknown - see disabled
    subdir: MinistroConfigurationTool
    target: android-16

AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: '1.0'
CurrentVersionCode: 1
