AntiFeatures:
  NonFreeNet:
    en-US: Rely on Shikimori.
Categories:
  - Multimedia
License: GPL-3.0-only
AuthorName: pewaru-333
SourceCode: https://github.com/pewaru-333/ShikiApp
IssueTracker: https://github.com/pewaru-333/ShikiApp/issues
Changelog: https://github.com/pewaru-333/ShikiApp/releases

AutoName: ShikiApp

RepoType: git
Repo: https://github.com/pewaru-333/ShikiApp
Binaries: https://github.com/pewaru-333/ShikiApp/releases/download/%v/ShikiApp.apk

Builds:
  - versionName: alpha-0.4.2
    versionCode: 27
    commit: ab7a1e7ef600d787713119c5feff779875a11114
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild:
      - mv $$OUT$$ unaligned.apk
      - $$reproducible-apk-tools$$/zipalign.py --page-size 16 --pad-like-apksigner
        --replace unaligned.apk $$OUT$$

  - versionName: alpha-0.4.3
    versionCode: 28
    commit: ab46a447a19f81f43c31f86fe30e6aa560da72aa
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild:
      - mv $$OUT$$ unaligned.apk
      - $$reproducible-apk-tools$$/zipalign.py --page-size 16 --pad-like-apksigner
        --replace unaligned.apk $$OUT$$

  - versionName: alpha-0.4.4
    versionCode: 29
    commit: 22e384949a610776341088b801b4dab0d6afa6c1
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild:
      - mv $$OUT$$ unaligned.apk
      - $$reproducible-apk-tools$$/zipalign.py --page-size 16 --pad-like-apksigner
        --replace unaligned.apk $$OUT$$

  - versionName: alpha-0.4.5
    versionCode: 30
    commit: 322b332ee57e0cd427dc3d55e034d46b88ac79b7
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild:
      - mv $$OUT$$ unaligned.apk
      - $$reproducible-apk-tools$$/zipalign.py --page-size 16 --pad-like-apksigner
        --replace unaligned.apk $$OUT$$

  - versionName: alpha-0.4.6
    versionCode: 31
    commit: eefbd275126c6c477231e9e0ecdd9dbf0fe840ee
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild:
      - mv $$OUT$$ unaligned.apk
      - $$reproducible-apk-tools$$/zipalign.py --page-size 16 --pad-like-apksigner
        --replace unaligned.apk $$OUT$$

AllowedAPKSigningKeys: b1a781cb8dbf7eb0dae9ff41972cb936e2ccf18b462defefbd0a21d3ac5f113d

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: alpha-0.4.6
CurrentVersionCode: 31
