Categories:
  - Development
License: GPL-3.0-only
WebSite: http://www.mayrhofer.eu.org/android-ipv6config

AutoName: IPv6Config
Summary: IPv6 Configuration Tool
Description: |-
  Provides the ability to configure some of the IPv6 kernel settings. Most
  importantly, it allows to automatically enable the "Privacy Extensions for
  Stateless Address Autoconfiguration in IPv6" as specified in IETF RFC4941 and
  implemented by the standard Linux kernel.

RequiresRoot: true

Builds:
  - versionName: '3.0'
    versionCode: 8
    commit: e687686
    rm:
      - donate
      - ant.properties

  - versionName: '4.0'
    versionCode: 9
    commit: 373378ccee009
    rm:
      - donate
      - ant.properties

MaintainerNotes: ant.properties is a symlink to outside the source tree

ArchivePolicy: 0
AutoUpdateMode: None
UpdateCheckMode: None
CurrentVersion: '4.0'
CurrentVersionCode: 9

NoSourceSince: '3.0'
