Connectivity:
  name: Aftësi lidhjeje
Development:
  name: Zhvillim
Games:
  name: Lojëra
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Para
Multimedia:
  name: Multimedia
Navigation:
  name: Lëvizje
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Lexim
Science & Education:
  name: Shkencë & Arsim
Security:
  name: Siguri
Sports & Health:
  name: Sporte & Shëndet
System:
  name: Sistem
Theming:
  name: Ndryshim teme grafike
Time:
  name: Kohë
Writing:
  name: Shkrim
Email:
  name: Email
VPN & Proxy:
  name: VPN & Ndërmjetës
DNS & Hosts:
  name: DNS & Strehë
AI Chat:
  name: Fjalosje IA
App Manager:
  name: Përgjegjës Aplikacionesh
App Store & Updater:
  name: Shitore & Përditësues Aplikacionesh
Bookmark:
  name: Faqerojtës
Browser:
  name: Shfletues
Calculator:
  name: Llogaritës
Calendar & Agenda:
  name: Kalendar & Plane
Cloud Storage & File Sync:
  name: Depozitim Në Re & Njëkohësim Kartelash
Draw:
  name: Vizatim
Ebook Reader:
  name: Lexues Elibrash
File Encryption & Vault:
  name: Fshehtëzim & Kasafortë Kartelash
File Transfer:
  name: Shpërngulje Kartelash
Finance Manager:
  name: Përgjegjës Financash
Forum:
  name: Forum
Gallery:
  name: Galeri
Habit Tracker:
  name: Ndjekës Zakonesh
Icon Pack:
  name: Paketë Ikonash
Keyboard & IME:
  name: Tastierë & IME
Launcher:
  name: Nisës
Local Media Player:
  name: Lojtës Mediash Vendore
Location Tracker & Sharer:
  name: Gjurmues & Dhënës Vendndodhjesh
Messaging:
  name: Shkëmbim Mesazhesh
Music Practice Tool:
  name: Mjet Praktimi Muzike
News:
  name: Lajme
Note:
  name: Shënim
Online Media Player:
  name: Lojtës Mediash Në Internet
Pass Wallet:
  name: Kuletë Fjalëkalimesh
Password & 2FA:
  name: Fjalëkalime & 2FA
Podcast:
  name: Podkast
Public Transport:
  name: Transport Publik
Recipe Manager:
  name: Përgjegjës Recetash Gatimi
Religion:
  name: Fe
Shopping List:
  name: Listë Blerjesh
Social Network:
  name: Rrjet Shoqëror
Task:
  name: Punë
Text Editor:
  name: Përpunues Tekstesh
Translation & Dictionary:
  name: Përkthim & Fjalor
Unit Convertor:
  name: Shndërrues Njësish
Voice & Video Chat:
  name: Fjalosje Me Zë & Video
Wallet:
  name: Kuletë
Wallpaper:
  name: Sfond
Weather:
  name: Mot
Clock:
  name: Sahat
Firewall:
  name: Firewall
Network Analyzer:
  name: Analizues Rrjeti
