Ads:
  description: Ứng dụng này có quảng cáo
  name: Quảng cáo
DisabledAlgorithm:
  description: Ứng dụng này có chữ kí bảo mật yếu
  name: Được ký bằng thuật toán không an toàn
KnownVuln:
  description: Ứng dụng này có một lỗ hổng bảo mật đã biết
  name: Lỗ hổng bảo mật đã biết
NSFW:
  description: Ứng dụng này có nội dung không nên hiển thị công khai ở mọi nơi
  name: NSFW
NoSourceSince:
  name: Không còn mã nguồn từ
  description: Mã nguồn không còn khả dụng, không còn được cập nhật
NonFreeAdd:
  description: Ứng dụng này quảng bá các tiện ích bổ sung không tự do
  name: Tiện ích mở rộng không tự do
NonFreeAssets:
  description: Ứng dụng này có những tài nguyên không tự do
  name: Tài nguyên không tự do
NonFreeDep:
  description: Ứng dụng này lệ thuộc vào các ứng dụng không tự do khác
  name: Lệ thuộc vào những thứ không tự do
NonFreeNet:
  description: Ứng dụng này quảng bá hoặc lệ thuộc hoàn toàn vào một dịch vụ mạng không tự do
  name: Dịch vụ mạng không tự do
Tracking:
  description: Ứng dụng này theo dõi và báo cáo hoạt động của bạn
  name: Theo dõi
TetheredNet:
  description: Ứng dụng này lệ thuộc hoàn toàn vào máy chủ cụ thể của một dịch vụ mạng
  name: Lệ thuộc hoàn toàn vào máy chủ cụ thể của một dịch vụ mạng
