Connectivity:
  name: Kết nối
Development:
  name: Lập trình
Games:
  name: Trò chơi
Graphics:
  name: Đồ hoạ
Internet:
  name: Internet
Money:
  name: Tài chính
Multimedia:
  name: Đa phương tiện
Navigation:
  name: Điều hướng
Phone & SMS:
  name: Gọi điện & SMS
Reading:
  name: Đọc
Science & Education:
  name: Khoa học & Giáo dục
Security:
  name: Bảo mật
Sports & Health:
  name: Thể thao & sức khoẻ
System:
  name: Hệ thống
Theming:
  name: Giao diện
Time:
  name: Thời gian
Writing:
  name: Soạn thảo
AI Chat:
  name: Trò chuyện AI
App Manager:
  name: Quản lý ứng dụng
App Store & Updater:
  name: Cửa hàng ứng dụng & Trình cập nhật
Bookmark:
  name: Dấu trang
Browser:
  name: Trình duyệt
Calculator:
  name: Máy tính bỏ túi
Calendar & Agenda:
  name: Lịch & Nhật trình
Clock:
  name: Đồng hồ
Cloud Storage & File Sync:
  name: Lưu trữ trên mây & Đồng bộ tệp
Contact:
  name: Danh bạ
DNS & Hosts:
  name: DNS & Máy chủ
Draw:
  name: Vẽ
Ebook Reader:
  name: Trình đọc ebook
Email:
  name: Email
File Encryption & Vault:
  name: Mã hóa và lưu trữ tệp
File Transfer:
  name: Gửi tệp
Finance Manager:
  name: Quản lý tài chính
Firewall:
  name: Tường lửa
Forum:
  name: Diễn đàn
Gallery:
  name: Thư viện ảnh
Habit Tracker:
  name: Theo dõi thói quen
Icon Pack:
  name: Gói biểu tượng
Inventory:
  name: Quản lý kho
Keyboard & IME:
  name: Bàn phím & IME
Launcher:
  name: Trình launcher
Local Media Player:
  name: Trình phát phương tiện offline
Location Tracker & Sharer:
  name: Định vị và chia sẻ vị trí
Messaging:
  name: Nhắn tin
Music Practice Tool:
  name: Công cụ luyện tập nhạc
Network Analyzer:
  name: Chẩn đoán mạng
News:
  name: Tin tức
Note:
  name: Ghi chú
Online Media Player:
  name: Trình phát phương tiện online
Pass Wallet:
  name: Ví giấy tờ
Password & 2FA:
  name: Mật khẩu & 2FA
Podcast:
  name: Podcast
Public Transport:
  name: Phương tiện giao thông
Recipe Manager:
  name: Quản lý công thức
Religion:
  name: Tôn giáo
Shopping List:
  name: Danh sách mua sắm
Social Network:
  name: Mạng xã hội
Task:
  name: Công việc
Text Editor:
  name: Trình soạn thảo
Translation & Dictionary:
  name: Dịch & Từ điển
Unit Convertor:
  name: Chuyển đổi đơn vị
Voice & Video Chat:
  name: Trò chuyện thoại và video
VPN & Proxy:
  name: VPN & Proxy
Wallet:
  name: Ví
Wallpaper:
  name: Hình nền
Weather:
  name: Thời tiết
Workout:
  name: Sức khỏe
