Connectivity:
  name: Kết nối
Development:
  name: Lập trình
Games:
  name: Trò chơi
Graphics:
  name: Đồ hoạ
Internet:
  name: Internet
Money:
  name: Tài chính
Multimedia:
  name: Đa phương tiện
Navigation:
  name: Điều hướng
Phone & SMS:
  name: Đàm thoại & nhắn tin
Reading:
  name: Đọc
Science & Education:
  name: Khoa học & giáo dục
Security:
  name: Bảo mật
Sports & Health:
  name: Thể thao & sức khoẻ
System:
  name: Hệ thống
Theming:
  name: Giao diện
Time:
  name: Thời gian
Writing:
  name: Soạn thảo
