Ads:
  name: Fógraí
  description: Tá fógraíocht san aip seo
DisabledAlgorithm:
  name: Arna shíniú Ag Úsáid Algartam Neamhshábháilte
  description: Tá síniú slándála lag ag an aip seo
KnownVuln:
  description: Tá leochaileacht slándála aitheanta san aip seo
  name: Leochaileacht Aitheanta
NSFW:
  description: Tá ábhar san aip seo nár cheart a phoibliú nó a fheiceáil i ngach áit
  name: NSFW
NoSourceSince:
  name: Gan Foinse Ó shin
  description: Níl an cód foinse ar fáil a thuilleadh, níl aon nuashonruithe indéanta
NonFreeDep:
  description: Braitheann an aip seo ar aipeanna eile nach bhfuil saor in aisce
  name: Spleáchais Neamh-Saor in Aisce
NonFreeNet:
  description: Cuireann an aip seo chun cinn nó braitheann sé go hiomlán ar sheirbhís líonra nach bhfuil saor in aisce
  name: Seirbhísí Líonra Neamh-Saor in Aisce
NonFreeAssets:
  description: Tá sócmhainní neamh-saor san aip seo
  name: Sócmhainní Neamh-Saor in Aisce
NonFreeAdd:
  description: Cuireann an aip seo breiseáin nach bhfuil saor in aisce chun cinn
  name: Breiseáin Neamh-Saor in Aisce
Tracking:
  description: Déanann an aip seo do ghníomhaíocht a rianú agus a thuairisciú
  name: Rianú
TetheredNet:
  description: Braitheann an aip seo go hiomlán ar shampla áirithe de sheirbhís líonra
  name: Seirbhísí Líonra Tethered
