Connectivity:
  name: Nascacht
Development:
  name: Forbairt
Games:
  name: Cluichí
Graphics:
  name: Grafaicí
Internet:
  name: Idirlíon
Reading:
  name: Léamh
Navigation:
  name: Loingseoireacht
Phone & SMS:
  name: Fón & SMS
Science & Education:
  name: Eolaíocht & Oideachas
Security:
  name: Slándáil
Sports & Health:
  name: Spóirt & Sláinte
System:
  name: Córas
Theming:
  name: Téamaí
Time:
  name: Am
Money:
  name: Airgead
Multimedia:
  name: Ilmheáin
Writing:
  name: Ag scríobh
Email:
  name: Ríomhphost
VPN & Proxy:
  name: VPN & Seachfhreastalaí
DNS & Hosts:
  name: DNS & Óstaigh
App Store & Updater:
  name: App Store & Nuashonraitheoir
Browser:
  name: Brabhsálaí
File Encryption & Vault:
  name: Criptiú Comhad & Cruinneachán
File Transfer:
  name: Aistriú Comhad
Social Network:
  name: Líonra Sóisialta
Local Media Player:
  name: Seinnteoir Meán Áitiúil
Weather:
  name: Aimsir
News:
  name: Nuacht
Online Media Player:
  name: Seinnteoir Meán Ar Líne
Password & 2FA:
  name: Pasfhocal agus 2FA
Podcast:
  name: Podchraoladh
Keyboard & IME:
  name: Méarchlár & IME
Messaging:
  name: Teachtaireachtaí
Bookmark:
  name: Leabharmharc
Calculator:
  name: Áireamhán
Calendar & Agenda:
  name: Féilire agus Clár Oibre
Cloud Storage & File Sync:
  name: Stóráil Néil & Sioncrónú Comhad
Draw:
  name: Tarraing
Ebook Reader:
  name: Léitheoir Ríomhleabhar
Finance Manager:
  name: Bainisteoir Airgeadais
Gallery:
  name: Gailearaí
Icon Pack:
  name: Pacáiste Deilbhíní
Launcher:
  name: Lainseálaí
Note:
  name: Nóta
Pass Wallet:
  name: Sparán Pas
Recipe Manager:
  name: Bainisteoir Oidis
Text Editor:
  name: Eagarthóir Téacs
Translation & Dictionary:
  name: Aistriúchán & Foclóir
Unit Convertor:
  name: Tiontaire Aonaid
Voice & Video Chat:
  name: Comhrá Gutha & Físeáin
Wallet:
  name: Sparán
Wallpaper:
  name: Páipéar balla
Workout:
  name: Babhta traenála
Public Transport:
  name: Léarscáil & Amchlár Iompair Phoiblí
Shopping List:
  name: Liosta Siopadóireachta
Task:
  name: Tasc
