Connectivity:
  name: Povezljivost
Development:
  name: Razvijanje
Games:
  name: Igre
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Denar
Multimedia:
  name: Multimedija
Navigation:
  name: Navigacija
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Branje
Science & Education:
  name: Znanost & Izobrazba
Security:
  name: Varnost
Sports & Health:
  name: Šport & zdravje
System:
  name: Sistem
Theming:
  name: Izgled
Time:
  name: Čas
Writing:
  name: Pisanje
App Store & Updater:
  name: App trgovina in posodobitve
Bookmark:
  name: Zaznamek
Browser:
  name: Brskalnik
Calculator:
  name: Kalkulator
Calendar & Agenda:
  name: Koledar in urnik
Cloud Storage & File Sync:
  name: Shranjevanje v oblaku in sinhronizacija datotek
DNS & Hosts:
  name: DNS in gostitelji
Draw:
  name: Riši
Ebook Reader:
  name: Bralnik e-knjig
Email:
  name: E-pošta
AI Chat:
  name: Klepet z UI
App Manager:
  name: Upravitelj orodij
Clock:
  name: Ura
Contact:
  name: Stiki
File Encryption & Vault:
  name: Šifriranje datotek in trezor
File Transfer:
  name: Posredovanje datotek
Finance Manager:
  name: Upravitelj financ
Firewall:
  name: Požarni zid
Forum:
  name: Klepetalnica
Gallery:
  name: Galerija
Habit Tracker:
  name: Sledilnik navad
Icon Pack:
  name: Zbirka ikon
Inventory:
  name: Popis imetja
Keyboard & IME:
  name: Tipkovnica in urejevalec vnosa IME
Launcher:
  name: Zaganjalnik
Local Media Player:
  name: Lokalni predvajalnik glasbe
Location Tracker & Sharer:
  name: Sledilnik in delilnik položaja
Messaging:
  name: Sporočila
Music Practice Tool:
  name: Orodje za vadbo glasbe
Network Analyzer:
  name: Pregledovalnik omrežja
News:
  name: Novice
Note:
  name: Beležka
Online Media Player:
  name: Predvajalnik spletnih vsebin
Password & 2FA:
  name: Gesla in dvostopenjsko preverjanje pristnosti
Podcast:
  name: Podkast
Public Transport:
  name: Javni prevoz
Recipe Manager:
  name: Upravitelj receptov
Religion:
  name: Vera
Shopping List:
  name: Nakupovalni seznam
Social Network:
  name: Družabna omrežja
Task:
  name: Opravila
Text Editor:
  name: Urejevalnik besedila
Translation & Dictionary:
  name: Prevajalec in slovar
Unit Convertor:
  name: Pretvornik enot
Voice & Video Chat:
  name: Glasovni in slikovni klepet
VPN & Proxy:
  name: VPN in posredniški strežniki (proxy)
Wallet:
  name: Denarnica
Wallpaper:
  name: Ozadja
Weather:
  name: Vreme
Workout:
  name: Telovadba
Pass Wallet:
  name: Denarnica kartic
