Ads:
  description: এই অ্যাপে বিজ্ঞাপন আছে
  icon: ic_antifeature_ads.png
DisabledAlgorithm:
  description: এই অ্যাপের নিরাপত্তা স্বাক্ষর খুব দুর্বল
  icon: ic_antifeature_disabledalgorithm.png
KnownVuln:
  description: এই অ্যাপের একটি জানা নিরাপত্তা দুর্বলতা রয়েছে
  icon: ic_antifeature_knownvuln.png
NSFW:
  icon: ic_antifeature_nsfw.png
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: উৎস কোড এখন অনুপভ্য, হালনাগাদ সম্ভব নয়।
NonFreeAdd:
  description: এই অ্যাপ অ-মুক্ত অ্যাড-অন ব্যবহারে উৎসাহিত করে
  icon: ic_antifeature_nonfreeadd.png
NonFreeAssets:
  description: এই অ্যাপে অ-মুক্ত উপাদান আছে
  icon: ic_antifeature_nonfreeassets.png
NonFreeDep:
  description: এই অ্যাপ অন্যান্য অ-মুক্ত অ্যাপের উপর নির্ভর করে
  icon: ic_antifeature_nonfreedep.png
NonFreeNet:
  description: এই অ্যাপ অ-মুক্ত নেটওয়ার্ক সেবা নিতে উৎসাহিত করে
  icon: ic_antifeature_nonfreenet.png
Tracking:
  description: এই অ্যাপটি আপনার কার্যকলাপ ট্র্যাক করে এবং বলে দেয়
  icon: ic_antifeature_tracking.png
UpstreamNonFree:
  description: উজানের কোড সম্পূর্ণরূপে মুক্ত না
  icon: ic_antifeature_upstreamnonfree.png
