Connectivity:
  name: Azday
Development:
  name: asbuɣlu
Games:
  name: uraren
Graphics:
  name: Tiwwunɣa
Internet:
  name: antirnit
Money:
  name: aẓeṛf
Reading:
  name: tiɣuri
Science & Education:
  name: Tamassant d usegmi
System:
  name: Anegraw
Time:
  name: Akud
Writing:
  name: Tirra
