Connectivity:
  name: 連線
Development:
  name: 開發
Games:
  name: 遊戲
Graphics:
  name: 圖形
Internet:
  name: 網際網路
Money:
  name: 理財
Multimedia:
  name: 多媒體
Navigation:
  name: 導航
Phone & SMS:
  name: 通話與簡訊
Reading:
  name: 閱讀
Science & Education:
  name: 科學與教育
Security:
  name: 安全性
Sports & Health:
  name: 運動與健康
System:
  name: 系統
Theming:
  name: 主題
Time:
  name: 時間
Writing:
  name: 書寫
Email:
  name: 電子郵件
VPN & Proxy:
  name: VPN 與代理伺服器
DNS & Hosts:
  name: DNS 與主機
AI Chat:
  name: AI 聊天
App Manager:
  name: 應用程式管理
App Store & Updater:
  name: 應用程式商店與更新程式
Bookmark:
  name: 書籤
Browser:
  name: 瀏覽器
Calculator:
  name: 計算機
Calendar & Agenda:
  name: 行事曆與日程
Clock:
  name: 時鐘
Cloud Storage & File Sync:
  name: 雲端儲存與檔案同步
Draw:
  name: 繪圖
Ebook Reader:
  name: 電子書閱讀器
File Encryption & Vault:
  name: 檔案加密與保險庫
File Transfer:
  name: 檔案傳輸
Finance Manager:
  name: 財務管理
Firewall:
  name: 防火牆
Forum:
  name: 論壇
Gallery:
  name: 圖庫
Habit Tracker:
  name: 習慣追蹤器
Icon Pack:
  name: 圖示套件
Inventory:
  name: 庫存
Keyboard & IME:
  name: 鍵盤與輸入法
Launcher:
  name: 啟動器
Local Media Player:
  name: 本機媒體播放器
Location Tracker & Sharer:
  name: 位置追蹤器與分享器
Messaging:
  name: 訊息傳遞
Music Practice Tool:
  name: 音樂練習工具
Contact:
  name: 聯絡
Network Analyzer:
  name: 網路分析工具
News:
  name: 新聞
Note:
  name: 記事
Online Media Player:
  name: 線上媒體播放器
Pass Wallet:
  name: 票證錢包
Password & 2FA:
  name: 密碼與兩步驟驗證
Podcast:
  name: 播客
Public Transport:
  name: 大眾運輸
Recipe Manager:
  name: 食譜管理
Religion:
  name: 宗教
Shopping List:
  name: 購物清單
Social Network:
  name: 社群網路
Task:
  name: 任務
Text Editor:
  name: 文字編輯器
Translation & Dictionary:
  name: 翻譯與辭典
Unit Convertor:
  name: 單位換算
Voice & Video Chat:
  name: 語音與視像聊天
Wallet:
  name: 錢包
Wallpaper:
  name: 背景圖片
Weather:
  name: 天氣
Workout:
  name: 健身
