Connectivity:
  name: 连接
Development:
  name: 开发
Games:
  name: 游戏
Graphics:
  name: 图像
Internet:
  name: 网络
Money:
  name: 理财
Multimedia:
  name: 多媒体
Navigation:
  name: 导航
Phone & SMS:
  name: 通话与短信
Reading:
  name: 阅读
Science & Education:
  name: 科学与教育
Security:
  name: 安全
Sports & Health:
  name: 运动与健康
System:
  name: 系统
Theming:
  name: 主题
Time:
  name: 时间
Writing:
  name: 记录
VPN & Proxy:
  name: VPN 和代理
Email:
  name: 电子邮件
DNS & Hosts:
  name: DNS & Hosts
File Transfer:
  name: 文件传输
Password & 2FA:
  name: 密码和双因素认证
Messaging:
  name: 消息收发
File Encryption & Vault:
  name: 文件加密和保险库
Social Network:
  name: 社交网络
App Store & Updater:
  name: 应用商店和更新工具
Browser:
  name: 浏览器
Local Media Player:
  name: 本地媒体播放器
News:
  name: 新闻
Online Media Player:
  name: 在线媒体播放器
Podcast:
  name: 播客
Weather:
  name: 天气
Keyboard & IME:
  name: 键盘和输入法
Cloud Storage & File Sync:
  name: 云存储和文件同步
Wallet:
  name: 钱包
Calendar & Agenda:
  name: 日历和日程
Voice & Video Chat:
  name: 音视频聊天
Bookmark:
  name: 书签
Calculator:
  name: 计算器
Draw:
  name: 绘图
Ebook Reader:
  name: 电子书阅读器
Finance Manager:
  name: 财务管理工具
Gallery:
  name: 相册
Icon Pack:
  name: 图标包
Launcher:
  name: 启动器
Note:
  name: 笔记
Pass Wallet:
  name: 卡包
Recipe Manager:
  name: 菜谱管理工具
Text Editor:
  name: 文本编辑器
Translation & Dictionary:
  name: 翻译和词典
Unit Convertor:
  name: 单位转换工具
Wallpaper:
  name: 壁纸
Workout:
  name: 锻炼
Public Transport:
  name: 公共交通地图和时间表
Task:
  name: 任务
Shopping List:
  name: 购物清单
