archive:
  description: F-Droid 自由软件仓库的存档。此处的应用年深日久，可能包含已知漏洞和安全问题！
  icon: fdroid-icon.png
  name: F-Droid 存档
repo:
  description: 官方 F-Droid 自由软件仓库。这个仓库中的一切始终是从源代码进行构建的。
  icon: fdroid-icon.png
  name: F-Droid
