Connectivity:
  name: Forbindelse
Development:
  name: Udvikling
Games:
  name: Spil
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Penge
Multimedia:
  name: Multimedier
Navigation:
  name: Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Læsning
Science & Education:
  name: Videnskab & Uddannelse
Security:
  name: Sikkerhed
Sports & Health:
  name: Sport & Sundhed
System:
  name: System
Theming:
  name: Temaer
Time:
  name: Tid
Writing:
  name: Skrivning
Browser:
  name: Browser
Email:
  name: E-mail
File Transfer:
  name: Filoverførsel
Forum:
  name: Forum
Gallery:
  name: Galleri
Icon Pack:
  name: Ikonpakke
Keyboard & IME:
  name: Tastatur og IME
Launcher:
  name: Launcher
Local Media Player:
  name: Lokal medieafspiller
News:
  name: Nyheder
Note:
  name: Note
Online Media Player:
  name: Online medieafspiller
Password & 2FA:
  name: Adgangskode og 2FA
Podcast:
  name: Podcast
Public Transport:
  name: Offentlig transport
Shopping List:
  name: Indkøbsliste
Task:
  name: Opgave
Text Editor:
  name: Tekstredigering
Translation & Dictionary:
  name: Oversættelse og ordbog
Voice & Video Chat:
  name: Stemme- og videochat
VPN & Proxy:
  name: VPN og proxy
Wallet:
  name: Pung
Wallpaper:
  name: Baggrund
Weather:
  name: Vejr
Workout:
  name: Træning
AI Chat:
  name: AI-chat
Calculator:
  name: Lommeregner
Calendar & Agenda:
  name: Kalender og dagsorden
Clock:
  name: Ur
Cloud Storage & File Sync:
  name: Cloudlager og filsynkronisering
Contact:
  name: Kontakt
DNS & Hosts:
  name: DNS og værter
Draw:
  name: Tegning
Ebook Reader:
  name: E-bogslæser
App Manager:
  name: Apphåndtering
App Store & Updater:
  name: Appbutik og -opdatering
Bookmark:
  name: Bogmærke
File Encryption & Vault:
  name: Filkryptering og boks
Finance Manager:
  name: Økonomihåndtering
Firewall:
  name: Firewall
Inventory:
  name: Inventar
