Connectivity:
  name: Konekteco
Development:
  name: Programado
Games:
  name: Ludoj
Graphics:
  name: Grafiko
Internet:
  name: Interreto
Money:
  name: Financoj
Multimedia:
  name: Sono kaj video
Navigation:
  name: Navigado
Phone & SMS:
  name: Telefonado kaj SMS
Reading:
  name: Legado
Science & Education:
  name: Scienco kaj edukado
Security:
  name: Sekureco
Sports & Health:
  name: Sporto kaj sano
System:
  name: Operaciumaj iloj
Theming:
  name: Haŭtoj (etosoj)
Time:
  name: Tempo
Writing:
  name: Skribado
Email:
  name: Retpoŝto
VPN & Proxy:
  name: VPN kaj retperiloj
DNS & Hosts:
  name: DNS kaj retgastigo
Social Network:
  name: Sociaj komunikiloj
App Store & Updater:
  name: Deponejoj kaj ĝisdatigiloj de aplikaĵoj
Browser:
  name: Retfoliumiloj
File Encryption & Vault:
  name: Dosiera ĉifrado
File Transfer:
  name: Dosiera kunhavigo
Keyboard & IME:
  name: Klavaroj
Local Media Player:
  name: Ludiloj de lokaj aŭdvidaĵoj
Messaging:
  name: Komunikiloj
News:
  name: Legiloj de novaĵoj
Online Media Player:
  name: Ludiloj de foraj aŭdvidaĵoj
Password & 2FA:
  name: Pasvort-administriloj kaj dupaŝaj aŭtentigiloj
Podcast:
  name: Ludiloj de aboneblaj sondosieroj (podkastoj)
Weather:
  name: Veterprognozo
Calendar & Agenda:
  name: Kalendaroj kaj tempplanoj
Cloud Storage & File Sync:
  name: Nuba konservado kaj dosiera samtempigo
Voice & Video Chat:
  name: Sonaj/videaj komunikiloj
Wallet:
  name: Monujoj
Calculator:
  name: Kalkuliloj
Draw:
  name: Desegnado
Ebook Reader:
  name: Legiloj de bitlibroj
Finance Manager:
  name: Financ-administriloj
Gallery:
  name: Bild-foliumiloj
Icon Pack:
  name: Bildsimbol-pakaĵoj
Launcher:
  name: Aplikaĵlanĉiloj
Note:
  name: Notlibroj
Pass Wallet:
  name: Biletujoj (por lojalec-kartoj)
Public Transport:
  name: Publika transporto (mapoj kaj forvetur-tabeloj)
Recipe Manager:
  name: Administriloj de kuir-receptoj
Task:
  name: Planiloj
Text Editor:
  name: Tekst-redaktiloj
Translation & Dictionary:
  name: Tradukiloj kaj vortaroj
Unit Convertor:
  name: Konvertiloj de unuoj
Wallpaper:
  name: Ekranfonoj
Workout:
  name: Trejnado
Bookmark:
  name: Administriloj de legosignoj
Shopping List:
  name: Listoj de aĉetoj
