Ads:
  description: Aplikasi ini berisi iklan
  name: Iklan
DisabledAlgorithm:
  description: Aplikasi ini memiliki tanda tangan keamanan yang lemah
  name: Ditandatangani Menggunakan Algoritma Tidak Aman
KnownVuln:
  description: Aplikasi ini berisi kerentanan keamanan yang dikenal
  name: Kerentanan yang Diketahui
NSFW:
  description: Aplikasi ini berisi konten yang tidak boleh dipublikasikan atau terlihat di mana-mana
  name: NSFW
NoSourceSince:
  name: Sumber tidak tersedia sejak
  description: Kode sumber tidak lagi tersedia, tidak mungkin melakukan pembaruan
NonFreeAdd:
  description: Aplikasi ini mempromosikan ekstensi non-bebas
  name: Ekstensi Non-Bebas
NonFreeAssets:
  description: Aplikasi ini mengandung aset non-bebas
  name: Aset Non-Bebas
NonFreeDep:
  description: Aplikasi ini bergantung pada aplikasi non-bebas lainnya
  name: Ketergantungan Non-Bebas
NonFreeNet:
  description: Aplikasi ini mempromosikan layanan jaringan non-bebas
  name: Layanan Jaringan Non-Bebas
Tracking:
  description: Aplikasi ini melacak dan melaporkan aktivitas Anda
  name: Pelacakan
TetheredNet:
  name: Layanan Jaringan Tertambat
  description: Aplikasi ini sepenuhnya bergantung pada layanan jaringan tertentu
