Ads:
  description: Esta aplicação contém publicidade
  name: Anúncios
DisabledAlgorithm:
  description: Esta aplicação tem uma assinatura de segurança fraca
  name: Assinado usando um algoritmo inseguro
KnownVuln:
  description: Esta aplicação contém uma falha de segurança conhecida
  name: Vulnerabilidade conhecida
NSFW:
  description: Esta aplicação contém conteúdo que não deve ser divulgado ou visível em todos os lugares
  name: NSFW
NoSourceSince:
  name: O código-fonte já não está disponível e não é possível atualizar.
NonFreeAdd:
  description: Esta aplicação promove add-ons não livres
  name: Complementos não livres
NonFreeAssets:
  description: Esta aplicação contém conteúdo não livre
  name: Ativos não livres
NonFreeDep:
  description: Esta aplicação depende de aplicações não livres
  name: Dependências não livres
NonFreeNet:
  description: Esta app promove ou depende inteiramente de um serviço de rede não livre
  name: Serviços de rede não livres
Tracking:
  description: Esta aplicação monitoriza e reporta a sua atividade
  name: Rastreamento
UpstreamNonFree:
  description: O código-fonte não é totalmente livre
  name: Upstream não livre
TetheredNet:
  name: Serviços de rede com fios
  description: Esta app depende inteiramente de uma determinada instância de um serviço de rede
