Connectivity:
  name: Tengingar
Development:
  name: Þróun
Games:
  name: Leikir
Graphics:
  name: Myndefni
Internet:
  name: Internetið
Money:
  name: Fjármál
Multimedia:
  name: Margmiðlun
Navigation:
  name: Yfirsýn
Phone & SMS:
  name: Símar og SMS
Reading:
  name: Lestur
Science & Education:
  name: Menntun og vísindi
Security:
  name: Öryggi
Sports & Health:
  name: Íþróttir og heilsa
System:
  name: Kerfið
Theming:
  name: Þemu
Time:
  name: Tími
Writing:
  name: Skrifa
