Ads:
  name: 有廣告
  description: 呢個 app 包含廣告
DisabledAlgorithm:
  description: 呢個 app 嘅簽署安全性薄弱
  name: 以唔安全嘅演算法簽署
NSFW:
  description: 呢個 app 啲料要睇就睇路，因住老細見到弊家伙
  name: 老細發威注意
NoSourceSince:
  name: 原始碼唔再提供，唔會再有更新。
NonFreeAdd:
  description: 呢個 app 推廣非自由嘅附加元件
  name: 附加元件非自由
NonFreeAssets:
  description: 呢個 app 包含非自由嘅資源
  name: 資源非自由
NonFreeDep:
  description: 呢個 app 依賴其他非自由嘅 app
  name: 依賴項目非自由
NonFreeNet:
  description: 呢個 app 推廣或完全依賴冇得改或非自由嘅網絡服務
  name: 網絡服務非自由
Tracking:
  description: 呢個 app 會追蹤同報告您嘅活動
  name: 會追蹤
UpstreamNonFree:
  description: 上游原始碼並非完全自由
  name: 上游非自由
TetheredNet:
  description: 呢個 app 推廣或完全依賴單一網絡服務。
  name: 獨家網絡服務
KnownVuln:
  description: 呢個 app 有已知嘅安全漏洞
  name: 有已知漏洞
