Connectivity:
  name: Connectivity
Development:
  name: Development
Games:
  name: Games
Graphics:
  name: Graphics
Internet:
  name: Internet
Money:
  name: Money
Multimedia:
  name: Multimedia
Navigation:
  name: Navigation
Phone & SMS:
  name: Phone & SMS
Reading:
  name: Reading
Science & Education:
  name: Science & Education
Security:
  name: Security
Sports & Health:
  name: Sports & Health
System:
  name: System
Theming:
  name: Theming
Time:
  name: Time
Writing:
  name: Writing
App Store & Updater:
  name: App Store & Updater
AI Chat:
  name: AI Chat
App Manager:
  name: App Manager
Bookmark:
  name: Bookmark
Browser:
  name: Browser
Calculator:
  name: Calculator
Calendar & Agenda:
  name: Calendar & Agenda
Clock:
  name: Clock
Cloud Storage & File Sync:
  name: Cloud Storage & File Sync
Contact:
  name: Contact
DNS & Hosts:
  name: DNS & Hosts
Draw:
  name: Draw
Ebook Reader:
  name: Ebook Reader
Email:
  name: Email
File Encryption & Vault:
  name: File Encryption & Vault
File Transfer:
  name: File Transfer
Finance Manager:
  name: Finance Manager
Firewall:
  name: Firewall
Forum:
  name: Forum
Gallery:
  name: Gallery
Habit Tracker:
  name: Habit Tracker
Icon Pack:
  name: Icon Pack
Inventory:
  name: Inventory
