Ads:
  description: Aquesta aplicació conté publicitat
  icon: ic_antifeature_ads.png
  name: Anuncis
DisabledAlgorithm:
  description: La signatura de seguretat de l'aplicació és feble
  icon: ic_antifeature_disabledalgorithm.png
  name: Signat amb un algoritme insegur
KnownVuln:
  description: Aquesta aplicació té un problema de seguretat conegut
  icon: ic_antifeature_knownvuln.png
  name: Vulnerabilitat coneguda
NSFW:
  description: Aquesta aplicació conté contingut que no s'ha de fer públic ni visible a tot arreu
  icon: ic_antifeature_nsfw.png
  name: NSFW (No apte per al treball)
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: El codi font ja no està disponible, no és possible actualitzar.
NonFreeAdd:
  description: Aquesta aplicació promou complements no lliures
  icon: ic_antifeature_nonfreeadd.png
  name: Complements no lliures
NonFreeAssets:
  description: Aquesta aplicació conté recursos no lliures
  icon: ic_antifeature_nonfreeassets.png
  name: Recursos no gratuïts
NonFreeDep:
  description: Aquesta aplicació depèn d'altres aplicacions no lliures
  icon: ic_antifeature_nonfreedep.png
  name: Dependències no lliures
NonFreeNet:
  description: Aquesta aplicació promou o depèn completament de serveis de xarxa no lliures
  icon: ic_antifeature_nonfreenet.png
  name: Serveis de xarxa no lliures
Tracking:
  description: Aquesta aplicació segueix i informa sobre la vostra activitat
  icon: ic_antifeature_tracking.png
  name: Seguiment
UpstreamNonFree:
  description: El codi font no és del tot lliure
  icon: ic_antifeature_upstreamnonfree.png
  name: Font no lliure
TetheredNet:
  description: Aquesta aplicació depèn completament d'algunes instàncies d'un servei de xarxa
  name: Serveis de Xarxes Vinculades (Tethered)
