Connectivity:
  name: Connectivitat
Development:
  name: Desenvolupament
Games:
  name: Jocs
Graphics:
  name: Gràfics
Internet:
  name: Internet
Money:
  name: Diners
Multimedia:
  name: Multimèdia
Navigation:
  name: Navegació
Phone & SMS:
  name: Mòbil i missatgeria
Reading:
  name: Lectura
Science & Education:
  name: Ciència i educació
Security:
  name: Seguretat
Sports & Health:
  name: Esports i Salut
System:
  name: Sistema
Theming:
  name: Temes
Time:
  name: Temps
Writing:
  name: Escriptura
App Store & Updater:
  name: Botiga d'aplicacions i actualitzador
Bookmark:
  name: Adreça d'interès
Browser:
  name: Navegador
Calculator:
  name: Calculadora
Calendar & Agenda:
  name: Calendaris i Agendes
Cloud Storage & File Sync:
  name: Emmagatzematge al núvol i sincronització d'arxius
DNS & Hosts:
  name: DNS i Allotjament
Draw:
  name: Dibuix
Ebook Reader:
  name: Lector de llibres electrònics
Email:
  name: Correu electrònic
File Encryption & Vault:
  name: Xifratge de fitxers i caixa forta
File Transfer:
  name: Transferències de fitxers
Finance Manager:
  name: Gestor de finances
Gallery:
  name: Galeria
Icon Pack:
  name: Pack d'icones
Keyboard & IME:
  name: Teclat i IME
Local Media Player:
  name: Reproductor local de mitjans
Messaging:
  name: Missatges
News:
  name: Notícies
Note:
  name: Notes
Online Media Player:
  name: Reproductor de mitjans en línia
Pass Wallet:
  name: Cartera de paraules de pas
Password & 2FA:
  name: Paraules de pas i autenticació de dos factors
Podcast:
  name: Podcast
Public Transport Map & Timetable:
  name: Mapa de transport públic i horaris
Recipe Manager:
  name: Gestor de receptes
Shopping List:
  name: Llista de compres
Social Network:
  name: Xarxes socials
Task:
  name: Tasques
Text Editor:
  name: Editor de text
Translation & Dictionary:
  name: Traducció i diccionari
Unit Convertor:
  name: Converso d'unitats
Voice & Video Chat:
  name: Xat de veu i vídeo
VPN & Proxy:
  name: VPN i Proxy
Wallet:
  name: Cartera
Wallpaper:
  name: Fons de pantalla
Weather:
  name: Clima
Workout:
  name: Entrenament
