Connectivity:
  name: இணைப்பு
Development:
  name: உருவாக்கம்
Games:
  name: விளையாட்டுகள்
Graphics:
  name: க்ராஃபிக்ஸ்
Internet:
  name: இணையம்
Money:
  name: பணம்
Multimedia:
  name: பல்லூடகம்
Navigation:
  name: வழிகாட்டல்
Phone & SMS:
  name: தொலைபேசி & குறுஞ்செய்தி
Reading:
  name: படித்தல்
Science & Education:
  name: அறிவியலும் கல்வியும்
Security:
  name: பாதுகாப்பு
Sports & Health:
  name: விளையாட்டும் உடல்நலமும்
System:
  name: அமைப்பு
Theming:
  name: தீமிங்
Time:
  name: நேரம்
Writing:
  name: எழுதுதல்
App Store & Updater:
  name: ஆப் கடை & அப்டேட்டர்
Bookmark:
  name: புத்தககுறி
Browser:
  name: உலாவி
Calculator:
  name: கணிப்பான்
Calendar & Agenda:
  name: காலண்டர் மற்றும் நிகழ்ச்சி நிரல்
Cloud Storage & File Sync:
  name: முகில் ச்டோரேச் & கோப்பு ஒத்திசைவு
DNS & Hosts:
  name: டி.என்.எச் & ஓச்ட்கள்
Draw:
  name: டிரா
Ebook Reader:
  name: மின்புத்தக வாசகர்
Email:
  name: மின்னஞ்சல்
File Encryption & Vault:
  name: கோப்பு குறியாக்கம் & பெட்டக
File Transfer:
  name: கோப்பு பரிமாற்றம்
Finance Manager:
  name: பொருள் மேலாளர்
Gallery:
  name: கேலரி
Icon Pack:
  name: படவுரு பேக்
Keyboard & IME:
  name: விசைப்பலகை & ime
Launcher:
  name: துவக்கி
Local Media Player:
  name: உள்ளக மீடியா பிளேயர்
Messaging:
  name: செய்தியிடல்
News:
  name: செய்தி
Note:
  name: குறிப்பு
Online Media Player:
  name: நிகழ்நிலை மீடியா பிளேயர்
Pass Wallet:
  name: பணப்பையை கடந்து செல்லுங்கள்
Password & 2FA:
  name: கடவுச்சொல் & 2FA
Podcast:
  name: போட்காச்ட்
Public Transport Map & Timetable:
  name: பொது போக்குவரத்து வரைபடம் & கால அட்டவணை
Recipe Manager:
  name: செய்முறை மேலாளர்
Shopping List:
  name: சாப்பிங் பட்டியல்
Social Network:
  name: சமூக வலைப்பின்னல்
Task:
  name: பணி
Text Editor:
  name: உரை ஆசிரியர்
Translation & Dictionary:
  name: மொழிபெயர்ப்பு மற்றும் அகராதி
Unit Convertor:
  name: ஒன்றுபட்டது மாற்றி
Voice & Video Chat:
  name: குரல் & வீடியோ அரட்டை
VPN & Proxy:
  name: VPN & பதிலாள்
Wallet:
  name: பணப்பையை
Wallpaper:
  name: வால்பேப்பர்
Weather:
  name: வானிலை
Workout:
  name: பயிற்சி
