Connectivity:
  name: Verbinden
Development:
  name: Ontwikkeling
Games:
  name: Spellen
Graphics:
  name: Grafisch
Internet:
  name: Internet
Money:
  name: Geld
Multimedia:
  name: Multimedia
Navigation:
  name: Navigatie
Phone & SMS:
  name: Telefoon & SMS
Reading:
  name: Lezen
Science & Education:
  name: Wetenschap & onderwijs
Security:
  name: Beveiliging
Sports & Health:
  name: Sport & gezondheid
System:
  name: Systeem
Theming:
  name: Thema's
Time:
  name: Tijd
Writing:
  name: Schrijven
AI Chat:
  name: AI-chat
App Manager:
  name: Appbeheerder
App Store & Updater:
  name: Appwinkel & updater
Bookmark:
  name: Bladwijzer
Browser:
  name: Browser
Calculator:
  name: Rekenmachine
Calendar & Agenda:
  name: Kalender & agenda
Clock:
  name: Klok
Cloud Storage & File Sync:
  name: Cloudopslag & bestandssynchronisatie
Contact:
  name: Contact
DNS & Hosts:
  name: DNS & hosts
Draw:
  name: Tekenen
Ebook Reader:
  name: E-boeklezer
Email:
  name: E-mail
File Encryption & Vault:
  name: Bestandsversleuteling & kluis
File Transfer:
  name: Bestandsoverdracht
Finance Manager:
  name: FinanciÃ«n beheren
Firewall:
  name: Firewall
Forum:
  name: Forum
Gallery:
  name: Galerij
Habit Tracker:
  name: Gewoontes bijhouden
Icon Pack:
  name: Pictogrammenpakket
Inventory:
  name: Inventarisatie
Keyboard & IME:
  name: Toetsenbord & invoer
Launcher:
  name: Launcher
Local Media Player:
  name: Lokale mediaspeler
Location Tracker & Sharer:
  name: Locatie bijhouden en delen
Messaging:
  name: Berichten
Music Practice Tool:
  name: Hulpmiddelen voor muzikanten
Network Analyzer:
  name: Netwerkanalyse
News:
  name: Nieuws
Note:
  name: Notities
Online Media Player:
  name: Online mediaspeler
Pass Wallet:
  name: Pasjesportemonnee
Password & 2FA:
  name: Wachtwoorden & 2FA
Podcast:
  name: Podcast
Public Transport:
  name: Openbaar vervoer
Recipe Manager:
  name: Receptenboek
Religion:
  name: Godsdienst
Shopping List:
  name: Boodschappenlijst
Social Network:
  name: Sociaal netwerk
Task:
  name: Taken
Text Editor:
  name: Tekstverwerker
Translation & Dictionary:
  name: Vertalen & woordenboek
Unit Convertor:
  name: Eenheden omrekenen
Voice & Video Chat:
  name: Bellen & videobellen
VPN & Proxy:
  name: VPN & proxy
Wallet:
  name: Portemonnee
Wallpaper:
  name: Achtergrond
Weather:
  name: Weer
Workout:
  name: Trainen & work-out
