Ads:
  description: This app contains advertising
  icon: ic_antifeature_ads.png
  name: Ads
DisabledAlgorithm:
  description: This app has a weak security signature
  icon: ic_antifeature_disabledalgorithm.png
  name: Signed Using An Unsafe Algorithm
KnownVuln:
  description: This app contains a known security vulnerability
  icon: ic_antifeature_knownvuln.png
  name: Known Vulnerability
NSFW:
  description: This app contains content that should not be publicized or visible everywhere
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: The source code is no longer available, no updates possible.
NonFreeAdd:
  description: This app promotes non-free add-ons
  icon: ic_antifeature_nonfreeadd.png
  name: Non-Free Addons
NonFreeAssets:
  description: This app contains non-free assets
  icon: ic_antifeature_nonfreeassets.png
  name: Non-Free Assets
NonFreeDep:
  description: This app depends on other non-free apps
  icon: ic_antifeature_nonfreedep.png
  name: Non-Free Dependencies
NonFreeNet:
  description: This app promotes or depends entirely on a non-free network service
  icon: ic_antifeature_nonfreenet.png
  name: Non-Free Network Services
Tracking:
  description: This app tracks and reports your activity
  icon: ic_antifeature_tracking.png
  name: Tracking
TetheredNet:
  description: This app depends entirely on a certain instance of a network service
  icon: ic_antifeature_tetherednet.png
  name: Tethered Network Services
UpstreamNonFree:
  description: The upstream source code is not entirely Free
  icon: ic_antifeature_upstreamnonfree.png
  name: Upstream Non-Free
