App Store & Updater:
  name: App Store & Updater
Bookmark:
  name: Bookmark
Browser:
  name: Browser
Calculator:
  name: Calculator
Calendar & Agenda:
  name: Calendar & Agenda
Cloud Storage & File Sync:
  name: Cloud Storage & File Sync
Connectivity:
  icon: category_connectivity.png
  name: Connectivity
Development:
  icon: category_development.png
  name: Development
DNS & Hosts:
  name: DNS & Hosts
Draw:
  name: Draw
Ebook Reader:
  name: Ebook Reader
Email:
  name: Email
File Encryption & Vault:
  name: File Encryption & Vault
File Transfer:
  name: File Transfer
Finance Manager:
  name: Finance Manager
Gallery:
  name: Gallery
Games:
  icon: category_games.png
  name: Games
Graphics:
  icon: category_graphics.png
  name: Graphics
Icon Pack:
  name: Icon Pack
Internet:
  icon: category_internet.png
  name: Internet
Keyboard & IME:
  name: Keyboard & IME
Launcher:
  name: Launcher
Local Media Player:
  name: Local Media Player
Messaging:
  name: Messaging
Money:
  icon: category_money.png
  name: Money
Multimedia:
  name: Multimedia
Navigation:
  icon: category_navigation.png
  name: Navigation
News:
  name: News
Note:
  name: Note
Online Media Player:
  name: Online Media Player
Pass Wallet:
  name: Pass Wallet
Password & 2FA:
  name: Password & 2FA
Phone & SMS:
  name: Phone & SMS
Podcast:
  name: Podcast
Public Transport Map & Timetable:
  name: Public Transport Map & Timetable
Reading:
  icon: category_reading.png
  name: Reading
Recipe Manager:
  name: Recipe Manager
Science & Education:
  icon: category_science_education.png
  name: Science & Education
Security:
  icon: category_security.png
  name: Security
Social Network:
  name: Social Network
Sports & Health:
  name: Sports & Health
System:
  icon: category_system.png
  name: System
Task:
  name: Task
Text Editor:
  name: Text Editor
Theming:
  icon: category_theming.png
  name: Theming
Time:
  name: Time
Translation & Dictionary:
  name: Translation & Dictionary
Unit Convertor:
  name: Unit Convertor
Voice & Video Chat:
  name: Voice & Video Chat
VPN & Proxy:
  name: VPN & Proxy
Wallet:
  name: Wallet
Wallpaper:
  name: Wallpaper
Weather:
  name: Weather
Workout:
  name: Workout
Writing:
  icon: category_writing.png
  name: Writing
