archive:
  description: မှတ်တမ်းဟောင်းများ -> ရှင်းလင်းချက်
  name: F-Droid Archive
repo:
  description: The official F-Droid Free Software repository. Everything in this repository is always built from the source code.
  name: F-Droid
