---

- url: http://fdroidorg6cooksyluodepej4erfctzk7rrjpjbbr6wx24jh3lqyfwyd.onion/fdroid

- url: http://dotsrccccbidkzg7oc7oj4ugxrlfbt64qebyunxbrgqhxiwj3nl6vcad.onion/fdroid

- url: http://ftpfaudev4triw2vxiwzf4334e3mynz7osqgtozhbc77fixncqzbyoyd.onion/fdroid

- url: http://lysator7eknrfl47rlyxvgeamrv7ucefgrrlhk7rouv3sna25asetwid.onion/pub/fdroid

- url: http://mirror.ossplanetnyou5xifr6liw5vhzwc2g2fmmlohza25wwgnnaw65ytfsad.onion/fdroid

- url: https://fdroid.tetaneutral.net/fdroid
  countryCode: FR

- url: https://ftp.agdsn.de/fdroid
  countryCode: DE

- url: https://ftp.fau.de/fdroid
  countryCode: DE

- url: https://ftp.gwdg.de/pub/android/fdroid
  countryCode: DE

- url: https://ftp.lysator.liu.se/pub/fdroid
  countryCode: SE

- url: https://mirror.cyberbits.eu/fdroid
  countryCode: FR

- url: https://mirror.fcix.net/fdroid
  countryCode: US

- url: https://mirror.kumi.systems/fdroid
  countryCode: AT

- url: https://mirror.level66.network/fdroid
  countryCode: DE

- url: https://mirror.ossplanet.net/fdroid
  countryCode: TW

- url: https://mirrors.dotsrc.org/fdroid
  countryCode: DK

- url: https://opencolo.mm.fcix.net/fdroid
  countryCode: US

- url: https://plug-mirror.rcac.purdue.edu/fdroid
  countryCode: US

- url: https://mirror.init7.net/fdroid
  countryCode: CH

- url: https://mirror.freedif.org/fdroid
  countryCode: SG

- url: https://de.freedif.org/fdroid
  countryCode: DE
