Ads:
  description: Приложението съдържа реклами
  name: Реклами
DisabledAlgorithm:
  description: Приложението има слаб подпис за защита
  name: Подписът е от несигурен алгоритъм
KnownVuln:
  description: Приложението има известна уязвимост в сигурността
  name: Известна уязвимост
NSFW:
  description: Съдържанието на приложението не трябва да бъде публикувано или видимо навсякъде
  name: 18+
NoSourceSince:
  name: Липсва изходен код от
  description: Изходният код не е наличен вече, не е възможно обновяване
NonFreeAdd:
  description: Приложението насърчава използване на добавки със затворен код
  name: Несвободни добавки
NonFreeAssets:
  description: Приложението съдържа несвободни компоненти
  name: Несвободни компоненти
NonFreeDep:
  description: Приложението зависи от други несвободни приложения
  name: Несвободни зависимости
NonFreeNet:
  description: Приложението насърчава използване на несвободни мрежови услуги
  name: Несвободни мрежови услуги
Tracking:
  description: Приложението следи и докладва действията ви
  name: Проследяване
TetheredNet:
  description: Приложението изцяло зависи от определен екземпляр на мрежова услуга
  name: Обвързани мрежови услуги
