Ads:
  description: Az alkalmazás reklámot tartalmaz
  name: Reklámok
DisabledAlgorithm:
  description: Az alkalmazásnak gyenge a biztonsági aláírása
  name: Nem biztonságos algoritmussal van aláírva
KnownVuln:
  description: Az alkalmazás ismert biztonsági rést tartalmaz
  name: Ismert sérülékenység
NSFW:
  description: Ez az alkalmazás olyan tartalommal rendelkezik, amelyet nem szabad mindenhol megjeleníteni
  name: NSFW
NoSourceSince:
  name: A forráskód többé nem érhető el, a frissítések nem lehetségesek.
NonFreeAdd:
  description: Az alkalmazás nem szabad kiegészítőket támogat
  name: Nem szabad kiegészítők
NonFreeAssets:
  description: Az alkalmazás nem szabad erőforrásokat tartalmaz
  name: Nem szabad erőforrások
NonFreeDep:
  description: Az alkalmazás egyéb, nem szabad alkalmazásoktól függ
  name: Nem szabad függőségek
NonFreeNet:
  description: Ez az alkalmazás nem módosítható vagy nem ingyenes hálózati szolgáltatást reklámoz, vagy teljes mértékben attól függ
  name: Nem szabad hálózati szolgáltatások
Tracking:
  description: Az alkalmazás nyomon követi és jelenti a tevékenységeit
  name: Követés
UpstreamNonFree:
  description: Az upstream forráskód nem teljesen szabad
  name: Nem szabad upstream forráskód
TetheredNet:
  description: Ez az alkalmazás teljes egészében egy hálózati szolgáltatás egy adott példányára támaszkodik vagy promotálja azt.
  name: Tethered/Pányvázott hálózatok
