Connectivity:
  name: Kapcsolódás
Development:
  name: Fejlesztés
Games:
  name: Játékok
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Pénzügyek
Multimedia:
  name: Multimédia
Navigation:
  name: Navigáció
Phone & SMS:
  name: Telefon és SMS
Reading:
  name: Olvasás
Science & Education:
  name: Tudomány és oktatás
Security:
  name: Biztonság
Sports & Health:
  name: Sport és egészség
System:
  name: Rendszer
Theming:
  name: Stílus
Time:
  name: Idő
Writing:
  name: Írás
DNS & Hosts:
  name: DNS és kiszolgálók
Email:
  name: E-mail
Offline Music & Video Player:
  name: Offline zene- és videólejátszó
Messaging:
  name: Üzenetküldés
Password & 2FA:
  name: Jelszavak és 2FA
Social Network:
  name: Közösségi hálózat
VPN & Proxy:
  name: VPN és proxy
File Transfer:
  name: Fájlátvitel
File Encryption & Vault:
  name: Fájltitkosítás és széfek
