Connectivity:
  name: Kapcsolódás
Development:
  name: Fejlesztés
Games:
  name: Játékok
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Pénzügyek
Multimedia:
  name: Multimédia
Navigation:
  name: Navigáció
Phone & SMS:
  name: Telefon és SMS
Reading:
  name: Olvasás
Science & Education:
  name: Tudomány és oktatás
Security:
  name: Biztonság
Sports & Health:
  name: Sport és egészség
System:
  name: Rendszer
Theming:
  name: Stílus
Time:
  name: Idő
Writing:
  name: Írás
DNS & Hosts:
  name: DNS és kiszolgálók
Email:
  name: E-mail
Messaging:
  name: Üzenetküldés
Password & 2FA:
  name: Jelszavak és 2FA
Social Network:
  name: Közösségi hálózat
VPN & Proxy:
  name: VPN és proxy
File Transfer:
  name: Fájlátvitel
File Encryption & Vault:
  name: Fájltitkosítás és széfek
Bookmark:
  name: Könyvjelző
Browser:
  name: Böngésző
Calculator:
  name: Számológép
Ebook Reader:
  name: E-könyv olvasó
Gallery:
  name: Galéria
Icon Pack:
  name: Ikoncsomag
News:
  name: Hírek
Note:
  name: Jegyzet
Online Media Player:
  name: Online médialejátszó
Recipe Manager:
  name: Receptkezelő
Shopping List:
  name: Bevásárlólista
Text Editor:
  name: Szövegszerkesztő
Wallet:
  name: Pénztárca
Wallpaper:
  name: Háttérkép
Weather:
  name: Időjárás
AI Chat:
  name: MI csevegés
App Manager:
  name: Alkalmazáskezelő
App Store & Updater:
  name: Alkalmazásbolt és -frissítő
Religion:
  name: Vallás
Calendar & Agenda:
  name: Naptár és napirend
Clock:
  name: Óra
Cloud Storage & File Sync:
  name: Felhős tárolás és fájlszinkronizálás
Draw:
  name: Rajzolás
Finance Manager:
  name: Pénzügykezelő
Firewall:
  name: Tűzfal
Forum:
  name: Fórum
Habit Tracker:
  name: Szokáskövető
Inventory:
  name: Leltár
Keyboard & IME:
  name: Billentyűzet és bevitelszerkesztő
Launcher:
  name: Indító
Local Media Player:
  name: Helyi médialejátszó
Location Tracker & Sharer:
  name: Helykövető és -megosztó
Music Practice Tool:
  name: Zenei gyakorló eszközök
Network Analyzer:
  name: Hálózatelemző
Pass Wallet:
  name: Jegytárca
Podcast:
  name: Podcast
Public Transport:
  name: Tömegközlekedés
Task:
  name: Feladat
Translation & Dictionary:
  name: Fordítás és szótár
Unit Convertor:
  name: Mértékegység-átváltó
Voice & Video Chat:
  name: Hang- és videócsevegés
Workout:
  name: Edzés
Contact:
  name: Névjegy
