Connectivity:
  name: Ryšiai ir tinklas
Development:
  name: Plėtojimas
Games:
  name: Žaidimai
Graphics:
  name: Grafika
Internet:
  name: Internetas
Money:
  name: Pinigai
Multimedia:
  name: Multimedija
Navigation:
  name: Navigacija
Phone & SMS:
  name: Telefonas ir SMS
Reading:
  name: Skaitymas
Science & Education:
  name: Mokslas ir švietimas
Security:
  name: Saugumas
Sports & Health:
  name: Sportas ir sveikata
System:
  name: Sistema
Theming:
  name: Apipavidalinimas
Time:
  name: Laikas
Writing:
  name: Rašymas
App Store & Updater:
  name: Programėlių parduotuvė ir atnaujintuvas
Bookmark:
  name: Žymė
Browser:
  name: Naršyklė
Calculator:
  name: Skaičiuotuvas
Calendar & Agenda:
  name: Kalendorius ir darbotvarkė
Cloud Storage & File Sync:
  name: Saugykla debesyje ir failų sinchronizavimas
DNS & Hosts:
  name: DNS ir serveriai
Ebook Reader:
  name: El. knygų skaityklė
Email:
  name: Elektroninis paštas
File Encryption & Vault:
  name: Failų šifravimas ir saugykla
File Transfer:
  name: Failų perkėlimas
Finance Manager:
  name: Finansų valdyklė
Gallery:
  name: Galerija
Icon Pack:
  name: Piktogramų pakas
Draw:
  name: Piešimas
Keyboard & IME:
  name: Klaviatūra ir įvesties metodai (IME)
Launcher:
  name: Paleidimo programa
Local Media Player:
  name: Vietinės medijos leistuvė
Messaging:
  name: Susirašinėjimas
News:
  name: Naujienos
Note:
  name: Pastaba
Online Media Player:
  name: Internetinė medijos leistuvė
Pass Wallet:
  name: Bilietų piniginė
Password & 2FA:
  name: Slaptažodžiai ir 2 fakt. autentif.
Podcast:
  name: Tinklalaidė
Public Transport Map & Timetable:
  name: Vieš. transp. žemėlapis ir tvarkaraštis
Recipe Manager:
  name: Receptų tvarkyklė
Shopping List:
  name: Pirkinių sąrašas
Social Network:
  name: Socialinis tinklas
Task:
  name: Užduotis
Text Editor:
  name: Tekstų redaktorius
Translation & Dictionary:
  name: Vertimas ir žodynas
Unit Convertor:
  name: Vienetų keitiklis
Voice & Video Chat:
  name: Balso ir garso pokalbiai
VPN & Proxy:
  name: VPN ir proxy
Wallet:
  name: Piniginė
Wallpaper:
  name: Užsklanda
Weather:
  name: Orai
Workout:
  name: Treniruotė
