Connectivity:
  name: Ühenduvus
Development:
  name: Arendus
Games:
  name: Mängud
Graphics:
  name: Graafika
Internet:
  name: Internet
Money:
  name: Raha
Multimedia:
  name: Multimeedia
Navigation:
  name: Navigeerimine
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Lugemine
Science & Education:
  name: Teadus & haridus
Security:
  name: Turvalisus
Sports & Health:
  name: Sport & tervis
System:
  name: Süsteem
Theming:
  name: Kujundused
Time:
  name: Aeg
Writing:
  name: Kirjutamine
VPN & Proxy:
  name: VPN ja proksiteenused
Email:
  name: E-post
DNS & Hosts:
  name: Nimelahendus ja hostid
App Store & Updater:
  name: Rakendustepood ja uuendused
Browser:
  name: Veebibrauserid
File Encryption & Vault:
  name: Failide krüptimine ja andmehoidlad
File Transfer:
  name: Failide edastamine
Messaging:
  name: Sõnumirakendused
News:
  name: Uudised
Local Media Player:
  name: Meediaesitus nutiseadmest
Online Media Player:
  name: Meediaesitus võrgust
Password & 2FA:
  name: Salasõnad ja 2FA
Social Network:
  name: Sotsiaalvõrgustik
Weather:
  name: Ilmaennustus
Keyboard & IME:
  name: Klahvistik ja sisendmeetodid
Podcast:
  name: Taskuhääling
Calendar & Agenda:
  name: Kalender ja päevakava
Voice & Video Chat:
  name: Hääl- ja videovestlused
Cloud Storage & File Sync:
  name: Andmeruum pilves ja failide sünkroonimine
Wallet:
  name: Dokumendi- ja rahataskud
Bookmark:
  name: Järjehoidjad
Calculator:
  name: Kalkulaatorid
Draw:
  name: Joonistamine
Ebook Reader:
  name: E-raamatute lugemine
Finance Manager:
  name: Rahahaldus
Gallery:
  name: Galeriid
Icon Pack:
  name: Ikoonipakid
Launcher:
  name: Käivitajad
Note:
  name: Märkmikud
Pass Wallet:
  name: Raha- ja kaarditaskud
Recipe Manager:
  name: Retseptihaldus
Text Editor:
  name: Tekstitoimetid
Translation & Dictionary:
  name: Tõlkimine ja sõnastikud
Unit Convertor:
  name: Ühikute teisendajad
Wallpaper:
  name: Taustapildid
Workout:
  name: Treening
