Money:
  name: Pesa
Graphics:
  name: Michoro
Phone & SMS:
  name: Simu na Huduma ya Ujumbe Fupi
Science & Education:
  name: Sayansi na Elimu
Security:
  name: Usalama
Sports & Health:
  name: Michezo na Afya
Time:
  name: Saa
Connectivity:
  name: Muunganisho
Development:
  name: Maendeleo
Games:
  name: Michezo
Internet:
  name: Mtandao
Multimedia:
  name: Multimedia
Navigation:
  name: Urambazaji
Reading:
  name: Kusoma
System:
  name: Mfumo
Theming:
  name: Mandhari
Writing:
  name: Kuandika
App Manager:
  name: Msimamizi wa Programu
App Store & Updater:
  name: Ghala la Programu
Bookmark:
  name: Alamisho
Browser:
  name: Kivinjari
Calculator:
  name: Kikokotoo
Calendar & Agenda:
  name: Kalenda na Ajenda
Clock:
  name: Saa
Cloud Storage & File Sync:
  name: Hifadhi ya Wingu na Usawazishaji wa Faili
Contact:
  name: Mawasiliano
DNS & Hosts:
  name: DNS & Wapangishi
Draw:
  name: Kuchora
