Money:
  name: Pesa
Graphics:
  name: Michoro
Phone & SMS:
  name: Simu na Huduma ya Ujumbe Fupi
Science & Education:
  name: Sayansi na Elimu
Security:
  name: Usalama
Sports & Health:
  name: Michezo na Afya
Time:
  name: Saa
Connectivity:
  name: Muunganisho
Development:
  name: Maendeleo
Games:
  name: Michezo
Internet:
  name: Mtandao
Multimedia:
  name: Multimedia
Navigation:
  name: Urambazaji
Reading:
  name: Kusoma
System:
  name: Mfumo
Theming:
  name: Mandhari
Writing:
  name: Kuandika
App Manager:
  name: Msimamizi wa Programu
App Store & Updater:
  name: Ghala la Programu
Bookmark:
  name: Alamisho
Browser:
  name: Kivinjari
Calculator:
  name: Kikokotoo
Calendar & Agenda:
  name: Kalenda na Ajenda
Clock:
  name: Saa
Cloud Storage & File Sync:
  name: Hifadhi ya Wingu na Usawazishaji wa Faili
Contact:
  name: Mawasiliano
DNS & Hosts:
  name: DNS & Wapangishi
Draw:
  name: Kuchora
Email:
  name: Barua pepe
File Transfer:
  name: Uhamisho wa faili
Forum:
  name: Jukwaa la majadiliano
Gallery:
  name: Matunzio
Habit Tracker:
  name: Kifuatilia Tabia
Inventory:
  name: Orodha ya Bidhaa
Local Media Player:
  name: Kicheza Midia ya Kifaa
Messaging:
  name: Ujumbe
Music Practice Tool:
  name: Zana ya Mazoezi ya Muziki
Network Analyzer:
  name: Kichanganuzi cha Mtandao
News:
  name: Habari
Note:
  name: Dokezo
Online Media Player:
  name: Kicheza Midia Mtandaoni
Podcast:
  name: Podikasti
Public Transport:
  name: Usafiri wa Umma
Religion:
  name: Dini
Shopping List:
  name: Orodha ya Manunuzi
Task:
  name: Kazi
Translation & Dictionary:
  name: Tafsiri na Kamusi
Unit Convertor:
  name: Kigeuzi cha Vipimo
Voice & Video Chat:
  name: Mazungumzo ya Sauti na Video
Wallet:
  name: Mkoba
Wallpaper:
  name: Picha ya Mandharinyuma
AI Chat:
  name: AI Chat
Ebook Reader:
  name: Kisomaji Ebook
File Encryption & Vault:
  name: Usimbaji wa Faili & Vault
Finance Manager:
  name: Meneja wa Fedha
Firewall:
  name: Firewall
