Ads:
  description: Esta aplicação contém publicidade
  icon: ic_antifeature_ads.png
  name: Anúncios
DisabledAlgorithm:
  description: Esta aplicação tem uma assinatura de segurança fraca
  icon: ic_antifeature_disabledalgorithm.png
  name: Assinado usando um algoritmo inseguro
KnownVuln:
  description: Esta aplicação contém uma falha de segurança conhecida
  icon: ic_antifeature_knownvuln.png
  name: Vulnerabilidade conhecida
NSFW:
  description: Esta aplicação contém conteúdo que não deve ser divulgado ou visível em todos os lugares
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: O código-fonte já não está disponível e não é possível atualizar.
NonFreeAdd:
  description: Esta aplicação promove add-ons não livres
  icon: ic_antifeature_nonfreeadd.png
  name: Complementos não livres
NonFreeAssets:
  description: Esta aplicação contém conteúdo não livre
  icon: ic_antifeature_nonfreeassets.png
  name: Ativos não livres
NonFreeDep:
  description: Esta aplicação depende de aplicações não livres
  icon: ic_antifeature_nonfreedep.png
  name: Dependências não livres
NonFreeNet:
  description: Esta app promove ou depende inteiramente de um serviço de rede não mutável ou não livre
  icon: ic_antifeature_nonfreenet.png
  name: Serviços de rede não livres
Tracking:
  description: Esta aplicação monitoriza e reporta a sua atividade
  icon: ic_antifeature_tracking.png
  name: Rastreamento
UpstreamNonFree:
  description: O código-fonte não é totalmente livre
  icon: ic_antifeature_upstreamnonfree.png
  name: Upstream não livre
TetheredNet:
  description: Esta app promove ou depende inteiramente de uma determinada instância de um serviço de rede.
  name: Serviços de rede com fios
