Ads:
  description: Cette application contient des publicités
  name: Publicités
DisabledAlgorithm:
  description: La signature de sécurité de cette application est faible
  name: Signé Par Un Algorithme Non Sécurisé
KnownVuln:
  description: Cette application présente une faille de sécurité connue
  name: Vulnérabilité Connue
NSFW:
  description: Cette application contient des contenus qui ne doivent pas être rendus publics ni visibles partout
  name: NSFW
NoSourceSince:
  name: Le code source n’est plus accessible, aucune mise à jour n’est possible.
NonFreeAdd:
  description: Cette application promeut des extensions propriétaires
  name: Extensions non libres
NonFreeAssets:
  description: Cette application comprend des éléments propriétaires
  name: Composants Propriétaires
NonFreeDep:
  description: Cette application s'appuie d'autres applications propriétaires
  name: Dépendances Propriétaires
NonFreeNet:
  description: Cette application dépends ou propose d'utiliser des services réseaux propriétaires
  name: Services Réseau Propriétaires
Tracking:
  description: Cette application suit et transmet votre activité
  name: Traçage
UpstreamNonFree:
  description: Le code source en amont n’est pas entièrement libre
  name: Code d'Origine Propriétaire
TetheredNet:
  description: Cette application dépend entièrement d'un service réseau particulier
  name: Services Réseau Dépendants
