Connectivity:
  name: Connectivité
Development:
  name: Développement
Games:
  name: Jeux
Graphics:
  name: Graphisme
Internet:
  name: Internet
Money:
  name: Finances
Multimedia:
  name: Multimédia
Navigation:
  name: Navigation
Phone & SMS:
  name: Téléphone et SMS
Reading:
  name: Lecture
Science & Education:
  name: Science et éducation
Security:
  name: Sécurité
Sports & Health:
  name: Sport et santé
System:
  name: Système
Theming:
  name: Personnalisation
Time:
  name: Temps
Writing:
  name: Écriture
Calendar & Agenda:
  name: Calendrier & Agenda
Cloud Storage & File Sync:
  name: Stockage dans le cloud & Synchronisation de fichiers
Messaging:
  name: Messagerie
News:
  name: Nouvelles
Social Network:
  name: Réseau social
Wallet:
  name: Portefeuille
Voice & Video Chat:
  name: Chat vocal & vidéo
Online Media Player:
  name: Lecteur multimédia en ligne
Password & 2FA:
  name: Mot de passe & A2F
Podcast:
  name: Podcast
Weather:
  name: Météo
VPN & Proxy:
  name: VPN & proxy
DNS & Hosts:
  name: DNS & Hôtes
Email:
  name: E-mail
App Store & Updater:
  name: Boutique d'applications & programme de mise à jour
Browser:
  name: Navigateur
File Encryption & Vault:
  name: Chiffrement de fichiers & Coffre-fort
File Transfer:
  name: Transfert de fichiers
Keyboard & IME:
  name: Clavier & IME
Local Media Player:
  name: Lecteur multimédia local
Bookmark:
  name: Signet
Calculator:
  name: Calculatrice
Draw:
  name: Dessiner
Ebook Reader:
  name: Liseuse électronique
Finance Manager:
  name: Gestionnaire de finances
Gallery:
  name: Galerie
Icon Pack:
  name: Pack d'icônes
Launcher:
  name: Lanceur
Note:
  name: Note
Pass Wallet:
  name: Portefeuille de pass
Recipe Manager:
  name: Gestionnaire de recettes
Text Editor:
  name: Éditeur de texte
Translation & Dictionary:
  name: Traduction & dictionnaire
Unit Convertor:
  name: Convertisseur d'unités
Wallpaper:
  name: Fonds d'écran
Workout:
  name: Entraînement
Public Transport:
  name: Transports en commun
Shopping List:
  name: Liste de courses
Task:
  name: Tâche
Forum:
  name: Forum
Habit Tracker:
  name: Suivi des habitudes
Music Practice Tool:
  name: Outil de pratique musicale
Location Tracker & Sharer:
  name: Suivi & partage de localisation
AI Chat:
  name: Chat IA
App Manager:
  name: Gestionnaire d'applications
Religion:
  name: Religion
Clock:
  name: Horloge
Firewall:
  name: Pare-feu
Inventory:
  name: Inventaire
Network Analyzer:
  name: Analyseur de réseau
Contact:
  name: Contact
