Ads:
  description: Ova aplikacija sadrži oglase
  name: Oglasi
DisabledAlgorithm:
  description: Ova aplikacija ima slab sigurnosni potpis
  name: Potpisano pomoću nesigurnog algoritma
KnownVuln:
  description: Ova aplikacija sadrži poznat sigurnosni problem
  name: Poznata ranjivost
NoSourceSince:
  name: Nema izvora od
  description: Izvorni kod više nije dostupan, ažuriranja nisu moguća
NonFreeAdd:
  description: Ova aplikacija promiče neslobodne dodatke
  name: Ne-slobodni podaci
NonFreeAssets:
  description: Ova aplikacija sadrži ne-slobodne resurse
  name: Ne-slobodni resursi
NonFreeDep:
  description: Ova aplikacija ovisi o drugim ne-slobodnim aplikacijama
  name: Ne-slobodne ovisnosti
NonFreeNet:
  description: Ova aplikacija promovira ne-slobodne mrežne usluge
  name: Ne-slobodne mrežne usluge
Tracking:
  description: Ova aplikacija prati i javlja tvoju aktivnost
  name: Praćenje
NSFW:
  description: Ova aplikacija sadrži sadržaj koji ne bi trebao biti objavljen ili vidljiv svugdje
  name: NSFW
TetheredNet:
  description: Ova aplikacija u potpunosti ovisi o određenoj instanci mrežne usluge
  name: Dijeljene mrežnih usluga
