Connectivity:
  name: Povezivanje
Development:
  name: Razvoj
Games:
  name: Igre
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Novac
Multimedia:
  name: Multimedija
Navigation:
  name: Navigacija
Phone & SMS:
  name: Mobitel i SMS
Reading:
  name: Čitanje
Science & Education:
  name: Znanost i obrazovanje
Security:
  name: Sigurnost
Sports & Health:
  name: Sport i zdravlje
System:
  name: Sustav
Theming:
  name: Teme
Time:
  name: Vrijeme
Writing:
  name: Pisanje
Wallpaper:
  name: Slika pozadine
Weather:
  name: Vrijeme
Task:
  name: Zadatak
Text Editor:
  name: Uređivač teksta
Translation & Dictionary:
  name: Prijevod i riječnik
Unit Convertor:
  name: Konverter jedinica
Voice & Video Chat:
  name: Glasovni i video chat
VPN & Proxy:
  name: VPN i proxy
Wallet:
  name: Novčanik
Workout:
  name: Trening
AI Chat:
  name: UI chat
App Manager:
  name: Upravljač aplikacijama
App Store & Updater:
  name: Trgovina aplikacija i ažuriranje
Bookmark:
  name: Zabilješka
Browser:
  name: Preglednik
Calculator:
  name: Kalkulator
Calendar & Agenda:
  name: Kalendar i planiranje termina
Clock:
  name: Sat
Cloud Storage & File Sync:
  name: Spremanje u oblaku i sinkronizacija datoteka
DNS & Hosts:
  name: DNS i host računala
Draw:
  name: Crtanje
Ebook Reader:
  name: Čitač e-knjiga
Email:
  name: E-mail
File Encryption & Vault:
  name: Šifriranje datoteka i trezor
File Transfer:
  name: Prijenos datoteka
Finance Manager:
  name: Upravljač financijama
Firewall:
  name: Vatrozid
Forum:
  name: Forum
Gallery:
  name: Galerija
Habit Tracker:
  name: Praćenje navika
Icon Pack:
  name: Paket ikona
Inventory:
  name: Inventar
Keyboard & IME:
  name: Tipkovnica i IME uređivač
Launcher:
  name: Pokretač
Local Media Player:
  name: Lokalni player medija
Location Tracker & Sharer:
  name: Praćenje i dijeljenje lokacije
Messaging:
  name: Razmjena poruka
Music Practice Tool:
  name: Alat za vježbanje glazbe
Network Analyzer:
  name: Analizator mreže
News:
  name: Vijesti
Note:
  name: Bilješka
Online Media Player:
  name: Online player medija
Pass Wallet:
  name: Novčanik za propusnice i kartice
Password & 2FA:
  name: Lozinka i dvofaktorska autentifikacija
Podcast:
  name: Podcast
Public Transport:
  name: Javni prijevoz
Recipe Manager:
  name: Upravljač receptima
Religion:
  name: Vjera
Shopping List:
  name: Popis za kupovinu
Social Network:
  name: Dreuštvena mreža
Contact:
  name: Kontakt
