archive_older: 3
apk_signing_key_block_list:
  # Hash calculated with `openssl x509 -in <pem file> -outform der | sha256sum`
  # https://android.googlesource.com/platform/build/+/refs/heads/main/target/product/security
  - a6ccc500ff0e7421200eb66a7fe174ef1b00e52ca91727070cbedf061ff76c35 # AOSP bluetooth.x509.pem
  - ce7b2b47ae2b7552c8f92cc29124279883041fb623a5f194a82c9bf15d492aa0 # AOSP cts_uicc_2021.x509.pem
  - 465983f7791f2abeb43ea2cbdc7f21a8260b72bc08a55c839fc1a43bc741a81e # AOSP media.x509.pem
  - e1dbadce60dc080d15b58a014b0dcf9400e24de23fa00b287a5a982bfebda2ee # AOSP networkstack.x509.pem
  - fae9122a8721d6e2a196d2224dffcf773c9127e2bb956cbddb40b009192ffdfd # AOSP nfc.x509.pem
  - c8a2e9bccf597c2fb6dc66bee293fc13f2fc47ec77bc6b2b0d52c11f51192ab8 # AOSP platform.x509.pem
  - abf21f9e2af1d881cc673fddcefa6ed9c269a437bd64b279cf45844cfd589126 # AOSP sdk_sandbox.x509.pem
  - 28bbfe4a7b97e74681dc55c2fbb6ccb8d6c74963733f6af6ae74d8c3a6e879fd # AOSP shared.x509.pem
  - a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc # AOSP testkey.x509.pem
