Ads:
  description: Diese App enthält Werbung
  icon: ic_antifeature_ads.png
  name: Werbung
DisabledAlgorithm:
  description: Diese App hat eine schwache Sicherheitssignatur
  icon: ic_antifeature_disabledalgorithm.png
  name: Mit einem unsicheren Algorithmus signiert
KnownVuln:
  description: Diese App enthält eine bekannte Sicherheitslücke
  icon: ic_antifeature_knownvuln.png
  name: Bekannte Sicherheitslücke
NSFW:
  description: Diese App enthält Inhalte, die nicht öffentlich gemacht werden oder überall sichtbar sein sollten
  icon: ic_antifeature_nsfw.png
  name: NSFW
NoSourceSince:
  icon: ic_antifeature_nosourcesince.png
  name: Der Quellcode ist nicht mehr erhältlich, keine Aktualisierungen möglich.
NonFreeAdd:
  description: Diese App bewirbt nicht-quelloffene Erweiterungen
  icon: ic_antifeature_nonfreeadd.png
  name: Nicht-quelloffene Erweiterungen
NonFreeAssets:
  description: Diese App enthält nicht-quelloffene Bestandteile
  icon: ic_antifeature_nonfreeassets.png
  name: Nicht-quelloffene Bestandteile
NonFreeDep:
  description: Diese App ist abhängig von anderen nicht-quelloffenen Apps
  icon: ic_antifeature_nonfreedep.png
  name: Nicht-quelloffene Abhängigkeiten
NonFreeNet:
  description: Diese App bewirbt einen nicht-änderbaren oder nicht-quelloffenen Netzwerkdienst oder benötigt ihn zwingend
  icon: ic_antifeature_nonfreenet.png
  name: Nicht-quelloffene Netzwerkdienste
Tracking:
  description: Diese App verfolgt und versendet Ihre Aktivitäten
  icon: ic_antifeature_tracking.png
  name: Tracking
UpstreamNonFree:
  description: Der Originalcode ist nicht völlig quelloffen
  icon: ic_antifeature_upstreamnonfree.png
  name: Originalcode nicht-quelloffen
TetheredNet:
  description: Diese App bewirbt eine bestimmte Instanz eines Netzwerkdienstes oder benötigt sie zwingend.
  name: Kabelgebundene Netzwerkdienste
