Ads:
  description: Diese App enthält Werbung
  name: Werbung
DisabledAlgorithm:
  description: Diese App hat eine schwache Sicherheitssignatur
  name: Mit einem unsicheren Algorithmus signiert
KnownVuln:
  description: Diese App enthält eine bekannte Sicherheitslücke
  name: Bekannte Sicherheitslücke
NSFW:
  description: Diese App enthält Inhalte, die nicht öffentlich gemacht werden oder überall sichtbar sein sollten
  name: NSFW
NoSourceSince:
  name: Keine Quelle seit
  description: Der Quellcode ist nicht mehr verfügbar, keine Aktualisierungen möglich
NonFreeAdd:
  description: Diese App bewirbt nicht-quelloffene Erweiterungen
  name: Nicht-quelloffene Erweiterungen
NonFreeAssets:
  description: Diese App enthält nicht-quelloffene Bestandteile
  name: Nicht-quelloffene Bestandteile
NonFreeDep:
  description: Diese App ist abhängig von anderen nicht-quelloffenen Apps
  name: Nicht-quelloffene Abhängigkeiten
NonFreeNet:
  description: Diese App bewirbt oder hängt vollständig von einem nicht-quelloffenen Netzwerkdienst ab
  name: Nicht-quelloffene Netzwerkdienste
Tracking:
  description: Diese App verfolgt und versendet Ihre Aktivitäten
  name: Tracking
TetheredNet:
  description: Diese App hängt vollständig von einer bestimmten Instanz eines Netzwerkdienstes ab
  name: Tethering-Netzwerkdienste
