Connectivity:
  name: Konnektivität
Development:
  name: Entwicklung
Games:
  name: Spiele
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Geld
Multimedia:
  name: Multimedia
Navigation:
  name: Navigation
Phone & SMS:
  name: Telefon / SMS
Reading:
  name: Lesen
Science & Education:
  name: Wissenschaft / Bildung
Security:
  name: Sicherheit
Sports & Health:
  name: Sport / Gesundheit
System:
  name: System
Theming:
  name: Aussehen
Time:
  name: Zeit
Writing:
  name: Schreiben
Email:
  name: E-Mail
VPN & Proxy:
  name: VPN / Proxy
DNS & Hosts:
  name: DNS / Hosts
File Transfer:
  name: Dateiübertragung
Messaging:
  name: Messaging
Password & 2FA:
  name: Passwort / 2FA
Social Network:
  name: Soziales Netzwerk
File Encryption & Vault:
  name: Dateiverschlüsselung / Tresor
App Store & Updater:
  name: App-Store / Updater
Browser:
  name: Browser
Online Media Player:
  name: Online-Mediaplayer
Podcast:
  name: Podcast
Weather:
  name: Wetter
News:
  name: Nachrichten
Keyboard & IME:
  name: Tastatur / IME
Local Media Player:
  name: Lokaler Mediaplayer
Cloud Storage & File Sync:
  name: Cloud-Speicher / Dateisynchronisierung
Calendar & Agenda:
  name: Kalender / Terminplaner
Voice & Video Chat:
  name: Sprach-/Video-Chat
Wallet:
  name: Wallet
Unit Convertor:
  name: Einheitenumrechner
Bookmark:
  name: Lesezeichen
Calculator:
  name: Rechner
Draw:
  name: Zeichnen
Ebook Reader:
  name: E-Book-Reader
Finance Manager:
  name: Finanzmanager
Gallery:
  name: Galerie
Icon Pack:
  name: Symbol-Paket
Launcher:
  name: Launcher
Note:
  name: Notiz
Text Editor:
  name: Texteditor
Translation & Dictionary:
  name: Übersetzung / Wörterbuch
Wallpaper:
  name: Hintergrundbild
Workout:
  name: Workout
Pass Wallet:
  name: Passcode-Wallet
Public Transport Map & Timetable:
  name: Öffentlicher Verkehr / Netz- und Fahrpläne
Task:
  name: Aufgaben
Shopping List:
  name: Einkaufsliste
