Connectivity:
  name: Tilkobling
Development:
  name: Utvikling
Games:
  name: Spill
Graphics:
  name: Grafikk
Internet:
  name: Internett
Money:
  name: Penger
Multimedia:
  name: Multimedia
Navigation:
  name: Navigasjon
Phone & SMS:
  name: Telefon og SMS
Reading:
  name: Lesing
Science & Education:
  name: Vitenskap & utdanning
Security:
  name: Sikkerhet
Sports & Health:
  name: Idrett og helse
System:
  name: System
Theming:
  name: Tilpasning
Time:
  name: Tid
Writing:
  name: Skriving
