Connectivity:
  name: Tilkobling
Development:
  name: Utvikling
Games:
  name: Spill
Graphics:
  name: Grafikk
Internet:
  name: Internett
Money:
  name: Penger
Multimedia:
  name: Multimedia
Navigation:
  name: Navigasjon
Phone & SMS:
  name: Telefon og SMS
Reading:
  name: Lesing
Science & Education:
  name: Vitenskap & utdanning
Security:
  name: Sikkerhet
Sports & Health:
  name: Idrett og helse
System:
  name: System
Theming:
  name: Tilpasning
Time:
  name: Tid
Writing:
  name: Skriving
Bookmark:
  name: Bokmerke
Calculator:
  name: Kalkulator
Calendar & Agenda:
  name: Kalender & Agenda
Cloud Storage & File Sync:
  name: Skylagring & Filsynkronisering
DNS & Hosts:
  name: DNS & Verter
Draw:
  name: Tegning
Ebook Reader:
  name: E-bok-leser
Email:
  name: E-post
File Encryption & Vault:
  name: Filkryptering & Hvelv
File Transfer:
  name: Filoverføring
Finance Manager:
  name: Finans
Forum:
  name: Forum
Gallery:
  name: Galleri
Habit Tracker:
  name: Vanesporer
Icon Pack:
  name: Ikonpakke
Keyboard & IME:
  name: Tastatur & Inndatametoder
Local Media Player:
  name: Lokal mediaspiller
Messaging:
  name: Meldinger
Music Practice Tool:
  name: Musikkøvingsverktøy
News:
  name: Nyheter
Note:
  name: Notater
Online Media Player:
  name: Nettmediaspiller
Password & 2FA:
  name: Passord & 2FA
Podcast:
  name: Podcast
Public Transport:
  name: Offentlig transport
Recipe Manager:
  name: Oppskrifter
Shopping List:
  name: Handleliste
Social Network:
  name: Sosialt nettverk
Task:
  name: Oppgaver
Text Editor:
  name: Tekstredigering
Translation & Dictionary:
  name: Oversettelse & Ordbok
Unit Convertor:
  name: Enhetskonvertering
Voice & Video Chat:
  name: Stemme- & Video-chat
VPN & Proxy:
  name: VPN & Mellomserver
Wallet:
  name: Lommebok
Wallpaper:
  name: Bakgrunn
Weather:
  name: Vær
Workout:
  name: Trening
App Store & Updater:
  name: App-butikker & Oppdatere
Browser:
  name: Nettleser
Launcher:
  name: Launcher
Pass Wallet:
  name: Lommebøker & Kort
Location Tracker & Sharer:
  name: Lokasjonssporer og -deling
AI Chat:
  name: KI-chat
Religion:
  name: Religion
App Manager:
  name: App-administrasjon
Clock:
  name: Klokke
Firewall:
  name: Brannmur
Inventory:
  name: Inventar
Network Analyzer:
  name: Nettverksanalyse
