Connectivity:
  name: Бәйләнеш
Development:
  name: Эшләү
Email:
  name: Email
File Transfer:
  name: Файлдарҙы тапшырыу
Games:
  name: Уйындар
Graphics:
  name: Графика
Internet:
  name: Интернет
Offline Music & Video Player:
  name: Офлайн музыка һәм видео-плеер
Messaging:
  name: Мессенджер
Money:
  name: Финанстар
Multimedia:
  name: Мультимедиа
Navigation:
  name: Навигация
Phone & SMS:
  name: Телефон һәм SMS
Reading:
  name: Уҡыу
Science & Education:
  name: Фән һәм Мәғариф
Security:
  name: Хәүефһеҙлек
Social Network:
  name: Социаль селтәр
System:
  name: Система
Theming:
  name: Тема
Time:
  name: Сәғәт
VPN & Proxy:
  name: VPN һәм прокси
Writing:
  name: Яҙмалар
File Encryption & Vault:
  name: Файлдарҙы шифрлау һәм Һаҡлағыс
Password & 2FA:
  name: Пароль һәм 2FA
DNS & Hosts:
  name: DNS һәм хост
Sports & Health:
  name: Спорт һәм Һаулыҡ
