Ads:
  description: Tato aplikace obsahuje reklamu
  name: Reklamy
DisabledAlgorithm:
  description: Tato aplikace má slabý bezpečnostní podpis
  name: Podepsáno pomocí málo bezpečného algoritmu
KnownVuln:
  description: Tato aplikace má známou zranitelnost v zabezpečení
  name: Známá zranitelnost
NSFW:
  description: Tato aplikace zahrnuje obsah, který by neměl být zveřejněný nebo viditelný na všech místech
  name: NSFW
NoSourceSince:
  name: Žádný zdroj od
  description: Zdrojový kód již není k dispozici, aktualizace nejsou možné
NonFreeAdd:
  description: Tato aplikace propaguje nesvobodné doplňky
  name: Nesvobodné doplňky
NonFreeAssets:
  description: Tato aplikace obsahuje nesvobodné části
  name: Nesvobodné části
NonFreeDep:
  description: Tato aplikace závisí na jiných nesvobodných aplikacích
  name: Nesvobodné závislosti
NonFreeNet:
  description: Tato aplikace propaguje nebo zcela závisí na nesvobodné síťové službě
  name: Nesvobodné síťové služby
Tracking:
  description: Tato aplikace zaznamenává a odesílá vaši aktivitu
  name: Sledování
TetheredNet:
  name: Provázáné síťové služby
  description: Tato aplikace zcela závisí na určité instanci síťové služby
