Connectivity:
  name: Spojení
Development:
  name: Vývoj
Games:
  name: Hry
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Peníze
Multimedia:
  name: Multimédia
Navigation:
  name: Navigace
Phone & SMS:
  name: Telefon a SMS
Reading:
  name: Čtení
Science & Education:
  name: Věda a vzdělání
Security:
  name: Zabezpečení
Sports & Health:
  name: Sport a zdraví
System:
  name: Systém
Theming:
  name: Vzhledy
Time:
  name: Čas
Writing:
  name: Psaní
Email:
  name: E-mail
VPN & Proxy:
  name: VPN a proxy
DNS & Hosts:
  name: DNS a hostitelé
File Encryption & Vault:
  name: Šifrování souborů a trezor
Browser:
  name: Prohlížeč
File Transfer:
  name: Přenos souborů
Online Media Player:
  name: Přehrávač online médií
Password & 2FA:
  name: Heslo a 2FA
Social Network:
  name: Sociální síť
Weather:
  name: Počasí
Podcast:
  name: Podcast
Keyboard & IME:
  name: Klávesnice a IME
Messaging:
  name: Posílání zpráv
News:
  name: Zprávy
Local Media Player:
  name: Přehrávač lokálních médií
Voice & Video Chat:
  name: Hlasový a video chat
Calendar & Agenda:
  name: Kalendář a agenda
Cloud Storage & File Sync:
  name: Cloudové úložiště a synchronizace souborů
Wallet:
  name: Peněženka
App Store & Updater:
  name: Obchod s aplikacemi a aktualizátor
